// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"starledger/ent/bill"
	"starledger/ent/predicate"
	"starledger/ent/serverlease"
	"starledger/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BillUpdate is the builder for updating Bill entities.
type BillUpdate struct {
	config
	hooks    []Hook
	mutation *BillMutation
}

// Where appends a list predicates to the BillUpdate builder.
func (_u *BillUpdate) Where(ps ...predicate.Bill) *BillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillUpdate) SetUpdatedAt(v time.Time) *BillUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *BillUpdate) SetTenantID(v int) *BillUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *BillUpdate) SetNillableTenantID(v *int) *BillUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetBillNo sets the "bill_no" field.
func (_u *BillUpdate) SetBillNo(v string) *BillUpdate {
	_u.mutation.SetBillNo(v)
	return _u
}

// SetNillableBillNo sets the "bill_no" field if the given value is not nil.
func (_u *BillUpdate) SetNillableBillNo(v *string) *BillUpdate {
	if v != nil {
		_u.SetBillNo(*v)
	}
	return _u
}

// SetBillType sets the "bill_type" field.
func (_u *BillUpdate) SetBillType(v string) *BillUpdate {
	_u.mutation.SetBillType(v)
	return _u
}

// SetNillableBillType sets the "bill_type" field if the given value is not nil.
func (_u *BillUpdate) SetNillableBillType(v *string) *BillUpdate {
	if v != nil {
		_u.SetBillType(*v)
	}
	return _u
}

// SetRelatedResourceID sets the "related_resource_id" field.
func (_u *BillUpdate) SetRelatedResourceID(v int) *BillUpdate {
	_u.mutation.SetRelatedResourceID(v)
	return _u
}

// SetNillableRelatedResourceID sets the "related_resource_id" field if the given value is not nil.
func (_u *BillUpdate) SetNillableRelatedResourceID(v *int) *BillUpdate {
	if v != nil {
		_u.SetRelatedResourceID(*v)
	}
	return _u
}

// ClearRelatedResourceID clears the value of the "related_resource_id" field.
func (_u *BillUpdate) ClearRelatedResourceID() *BillUpdate {
	_u.mutation.ClearRelatedResourceID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BillUpdate) SetAmount(v float64) *BillUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BillUpdate) SetNillableAmount(v *float64) *BillUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BillUpdate) AddAmount(v float64) *BillUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBillDate sets the "bill_date" field.
func (_u *BillUpdate) SetBillDate(v time.Time) *BillUpdate {
	_u.mutation.SetBillDate(v)
	return _u
}

// SetNillableBillDate sets the "bill_date" field if the given value is not nil.
func (_u *BillUpdate) SetNillableBillDate(v *time.Time) *BillUpdate {
	if v != nil {
		_u.SetBillDate(*v)
	}
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *BillUpdate) SetDueDate(v time.Time) *BillUpdate {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *BillUpdate) SetNillableDueDate(v *time.Time) *BillUpdate {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// SetPaidDate sets the "paid_date" field.
func (_u *BillUpdate) SetPaidDate(v time.Time) *BillUpdate {
	_u.mutation.SetPaidDate(v)
	return _u
}

// SetNillablePaidDate sets the "paid_date" field if the given value is not nil.
func (_u *BillUpdate) SetNillablePaidDate(v *time.Time) *BillUpdate {
	if v != nil {
		_u.SetPaidDate(*v)
	}
	return _u
}

// ClearPaidDate clears the value of the "paid_date" field.
func (_u *BillUpdate) ClearPaidDate() *BillUpdate {
	_u.mutation.ClearPaidDate()
	return _u
}

// SetPaymentStatus sets the "payment_status" field.
func (_u *BillUpdate) SetPaymentStatus(v bill.PaymentStatus) *BillUpdate {
	_u.mutation.SetPaymentStatus(v)
	return _u
}

// SetNillablePaymentStatus sets the "payment_status" field if the given value is not nil.
func (_u *BillUpdate) SetNillablePaymentStatus(v *bill.PaymentStatus) *BillUpdate {
	if v != nil {
		_u.SetPaymentStatus(*v)
	}
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *BillUpdate) SetPaymentMethod(v string) *BillUpdate {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *BillUpdate) SetNillablePaymentMethod(v *string) *BillUpdate {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetInvoiceNo sets the "invoice_no" field.
func (_u *BillUpdate) SetInvoiceNo(v string) *BillUpdate {
	_u.mutation.SetInvoiceNo(v)
	return _u
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_u *BillUpdate) SetNillableInvoiceNo(v *string) *BillUpdate {
	if v != nil {
		_u.SetInvoiceNo(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *BillUpdate) SetRemark(v string) *BillUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *BillUpdate) SetNillableRemark(v *string) *BillUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *BillUpdate) SetTenant(v *Tenant) *BillUpdate {
	return _u.SetTenantID(v.ID)
}

// SetServerLeaseID sets the "server_lease" edge to the ServerLease entity by ID.
func (_u *BillUpdate) SetServerLeaseID(id int) *BillUpdate {
	_u.mutation.SetServerLeaseID(id)
	return _u
}

// SetNillableServerLeaseID sets the "server_lease" edge to the ServerLease entity by ID if the given value is not nil.
func (_u *BillUpdate) SetNillableServerLeaseID(id *int) *BillUpdate {
	if id != nil {
		_u = _u.SetServerLeaseID(*id)
	}
	return _u
}

// SetServerLease sets the "server_lease" edge to the ServerLease entity.
func (_u *BillUpdate) SetServerLease(v *ServerLease) *BillUpdate {
	return _u.SetServerLeaseID(v.ID)
}

// Mutation returns the BillMutation object of the builder.
func (_u *BillUpdate) Mutation() *BillMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *BillUpdate) ClearTenant() *BillUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearServerLease clears the "server_lease" edge to the ServerLease entity.
func (_u *BillUpdate) ClearServerLease() *BillUpdate {
	_u.mutation.ClearServerLease()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BillUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillUpdate) check() error {
	if v, ok := _u.mutation.BillNo(); ok {
		if err := bill.BillNoValidator(v); err != nil {
			return &ValidationError{Name: "bill_no", err: fmt.Errorf(`ent: validator failed for field "Bill.bill_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillType(); ok {
		if err := bill.BillTypeValidator(v); err != nil {
			return &ValidationError{Name: "bill_type", err: fmt.Errorf(`ent: validator failed for field "Bill.bill_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentStatus(); ok {
		if err := bill.PaymentStatusValidator(v); err != nil {
			return &ValidationError{Name: "payment_status", err: fmt.Errorf(`ent: validator failed for field "Bill.payment_status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Bill.tenant"`)
	}
	return nil
}

func (_u *BillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bill.Table, bill.Columns, sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bill.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BillNo(); ok {
		_spec.SetField(bill.FieldBillNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillType(); ok {
		_spec.SetField(bill.FieldBillType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(bill.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(bill.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BillDate(); ok {
		_spec.SetField(bill.FieldBillDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(bill.FieldDueDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaidDate(); ok {
		_spec.SetField(bill.FieldPaidDate, field.TypeTime, value)
	}
	if _u.mutation.PaidDateCleared() {
		_spec.ClearField(bill.FieldPaidDate, field.TypeTime)
	}
	if value, ok := _u.mutation.PaymentStatus(); ok {
		_spec.SetField(bill.FieldPaymentStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(bill.FieldPaymentMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceNo(); ok {
		_spec.SetField(bill.FieldInvoiceNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(bill.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.TenantTable,
			Columns: []string{bill.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.TenantTable,
			Columns: []string{bill.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServerLeaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.ServerLeaseTable,
			Columns: []string{bill.ServerLeaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverlease.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerLeaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.ServerLeaseTable,
			Columns: []string{bill.ServerLeaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverlease.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BillUpdateOne is the builder for updating a single Bill entity.
type BillUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BillMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillUpdateOne) SetUpdatedAt(v time.Time) *BillUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *BillUpdateOne) SetTenantID(v int) *BillUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillableTenantID(v *int) *BillUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetBillNo sets the "bill_no" field.
func (_u *BillUpdateOne) SetBillNo(v string) *BillUpdateOne {
	_u.mutation.SetBillNo(v)
	return _u
}

// SetNillableBillNo sets the "bill_no" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillableBillNo(v *string) *BillUpdateOne {
	if v != nil {
		_u.SetBillNo(*v)
	}
	return _u
}

// SetBillType sets the "bill_type" field.
func (_u *BillUpdateOne) SetBillType(v string) *BillUpdateOne {
	_u.mutation.SetBillType(v)
	return _u
}

// SetNillableBillType sets the "bill_type" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillableBillType(v *string) *BillUpdateOne {
	if v != nil {
		_u.SetBillType(*v)
	}
	return _u
}

// SetRelatedResourceID sets the "related_resource_id" field.
func (_u *BillUpdateOne) SetRelatedResourceID(v int) *BillUpdateOne {
	_u.mutation.SetRelatedResourceID(v)
	return _u
}

// SetNillableRelatedResourceID sets the "related_resource_id" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillableRelatedResourceID(v *int) *BillUpdateOne {
	if v != nil {
		_u.SetRelatedResourceID(*v)
	}
	return _u
}

// ClearRelatedResourceID clears the value of the "related_resource_id" field.
func (_u *BillUpdateOne) ClearRelatedResourceID() *BillUpdateOne {
	_u.mutation.ClearRelatedResourceID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BillUpdateOne) SetAmount(v float64) *BillUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillableAmount(v *float64) *BillUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BillUpdateOne) AddAmount(v float64) *BillUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBillDate sets the "bill_date" field.
func (_u *BillUpdateOne) SetBillDate(v time.Time) *BillUpdateOne {
	_u.mutation.SetBillDate(v)
	return _u
}

// SetNillableBillDate sets the "bill_date" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillableBillDate(v *time.Time) *BillUpdateOne {
	if v != nil {
		_u.SetBillDate(*v)
	}
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *BillUpdateOne) SetDueDate(v time.Time) *BillUpdateOne {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillableDueDate(v *time.Time) *BillUpdateOne {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// SetPaidDate sets the "paid_date" field.
func (_u *BillUpdateOne) SetPaidDate(v time.Time) *BillUpdateOne {
	_u.mutation.SetPaidDate(v)
	return _u
}

// SetNillablePaidDate sets the "paid_date" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillablePaidDate(v *time.Time) *BillUpdateOne {
	if v != nil {
		_u.SetPaidDate(*v)
	}
	return _u
}

// ClearPaidDate clears the value of the "paid_date" field.
func (_u *BillUpdateOne) ClearPaidDate() *BillUpdateOne {
	_u.mutation.ClearPaidDate()
	return _u
}

// SetPaymentStatus sets the "payment_status" field.
func (_u *BillUpdateOne) SetPaymentStatus(v bill.PaymentStatus) *BillUpdateOne {
	_u.mutation.SetPaymentStatus(v)
	return _u
}

// SetNillablePaymentStatus sets the "payment_status" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillablePaymentStatus(v *bill.PaymentStatus) *BillUpdateOne {
	if v != nil {
		_u.SetPaymentStatus(*v)
	}
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *BillUpdateOne) SetPaymentMethod(v string) *BillUpdateOne {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillablePaymentMethod(v *string) *BillUpdateOne {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetInvoiceNo sets the "invoice_no" field.
func (_u *BillUpdateOne) SetInvoiceNo(v string) *BillUpdateOne {
	_u.mutation.SetInvoiceNo(v)
	return _u
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillableInvoiceNo(v *string) *BillUpdateOne {
	if v != nil {
		_u.SetInvoiceNo(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *BillUpdateOne) SetRemark(v string) *BillUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *BillUpdateOne) SetNillableRemark(v *string) *BillUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *BillUpdateOne) SetTenant(v *Tenant) *BillUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetServerLeaseID sets the "server_lease" edge to the ServerLease entity by ID.
func (_u *BillUpdateOne) SetServerLeaseID(id int) *BillUpdateOne {
	_u.mutation.SetServerLeaseID(id)
	return _u
}

// SetNillableServerLeaseID sets the "server_lease" edge to the ServerLease entity by ID if the given value is not nil.
func (_u *BillUpdateOne) SetNillableServerLeaseID(id *int) *BillUpdateOne {
	if id != nil {
		_u = _u.SetServerLeaseID(*id)
	}
	return _u
}

// SetServerLease sets the "server_lease" edge to the ServerLease entity.
func (_u *BillUpdateOne) SetServerLease(v *ServerLease) *BillUpdateOne {
	return _u.SetServerLeaseID(v.ID)
}

// Mutation returns the BillMutation object of the builder.
func (_u *BillUpdateOne) Mutation() *BillMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *BillUpdateOne) ClearTenant() *BillUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearServerLease clears the "server_lease" edge to the ServerLease entity.
func (_u *BillUpdateOne) ClearServerLease() *BillUpdateOne {
	_u.mutation.ClearServerLease()
	return _u
}

// Where appends a list predicates to the BillUpdate builder.
func (_u *BillUpdateOne) Where(ps ...predicate.Bill) *BillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BillUpdateOne) Select(field string, fields ...string) *BillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Bill entity.
func (_u *BillUpdateOne) Save(ctx context.Context) (*Bill, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillUpdateOne) SaveX(ctx context.Context) *Bill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillUpdateOne) check() error {
	if v, ok := _u.mutation.BillNo(); ok {
		if err := bill.BillNoValidator(v); err != nil {
			return &ValidationError{Name: "bill_no", err: fmt.Errorf(`ent: validator failed for field "Bill.bill_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillType(); ok {
		if err := bill.BillTypeValidator(v); err != nil {
			return &ValidationError{Name: "bill_type", err: fmt.Errorf(`ent: validator failed for field "Bill.bill_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentStatus(); ok {
		if err := bill.PaymentStatusValidator(v); err != nil {
			return &ValidationError{Name: "payment_status", err: fmt.Errorf(`ent: validator failed for field "Bill.payment_status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Bill.tenant"`)
	}
	return nil
}

func (_u *BillUpdateOne) sqlSave(ctx context.Context) (_node *Bill, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bill.Table, bill.Columns, sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Bill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bill.FieldID)
		for _, f := range fields {
			if !bill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bill.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BillNo(); ok {
		_spec.SetField(bill.FieldBillNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillType(); ok {
		_spec.SetField(bill.FieldBillType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(bill.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(bill.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BillDate(); ok {
		_spec.SetField(bill.FieldBillDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(bill.FieldDueDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaidDate(); ok {
		_spec.SetField(bill.FieldPaidDate, field.TypeTime, value)
	}
	if _u.mutation.PaidDateCleared() {
		_spec.ClearField(bill.FieldPaidDate, field.TypeTime)
	}
	if value, ok := _u.mutation.PaymentStatus(); ok {
		_spec.SetField(bill.FieldPaymentStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(bill.FieldPaymentMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceNo(); ok {
		_spec.SetField(bill.FieldInvoiceNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(bill.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.TenantTable,
			Columns: []string{bill.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.TenantTable,
			Columns: []string{bill.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServerLeaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.ServerLeaseTable,
			Columns: []string{bill.ServerLeaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverlease.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerLeaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.ServerLeaseTable,
			Columns: []string{bill.ServerLeaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverlease.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Bill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
