// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"starledger/ent/contract"
	"starledger/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContractCreate is the builder for creating a Contract entity.
type ContractCreate struct {
	config
	mutation *ContractMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContractCreate) SetCreatedAt(v time.Time) *ContractCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContractCreate) SetNillableCreatedAt(v *time.Time) *ContractCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ContractCreate) SetUpdatedAt(v time.Time) *ContractCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ContractCreate) SetNillableUpdatedAt(v *time.Time) *ContractCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ContractCreate) SetTenantID(v int) *ContractCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ContractCreate) SetTitle(v string) *ContractCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetPartyA sets the "party_a" field.
func (_c *ContractCreate) SetPartyA(v string) *ContractCreate {
	_c.mutation.SetPartyA(v)
	return _c
}

// SetNillablePartyA sets the "party_a" field if the given value is not nil.
func (_c *ContractCreate) SetNillablePartyA(v *string) *ContractCreate {
	if v != nil {
		_c.SetPartyA(*v)
	}
	return _c
}

// SetPartyB sets the "party_b" field.
func (_c *ContractCreate) SetPartyB(v string) *ContractCreate {
	_c.mutation.SetPartyB(v)
	return _c
}

// SetNillablePartyB sets the "party_b" field if the given value is not nil.
func (_c *ContractCreate) SetNillablePartyB(v *string) *ContractCreate {
	if v != nil {
		_c.SetPartyB(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ContractCreate) SetAmount(v float64) *ContractCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ContractCreate) SetNillableAmount(v *float64) *ContractCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *ContractCreate) SetStartDate(v time.Time) *ContractCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_c *ContractCreate) SetNillableStartDate(v *time.Time) *ContractCreate {
	if v != nil {
		_c.SetStartDate(*v)
	}
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *ContractCreate) SetEndDate(v time.Time) *ContractCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ContractCreate) SetStatus(v contract.Status) *ContractCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ContractCreate) SetNillableStatus(v *contract.Status) *ContractCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetFileURL sets the "file_url" field.
func (_c *ContractCreate) SetFileURL(v string) *ContractCreate {
	_c.mutation.SetFileURL(v)
	return _c
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_c *ContractCreate) SetNillableFileURL(v *string) *ContractCreate {
	if v != nil {
		_c.SetFileURL(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *ContractCreate) SetRemark(v string) *ContractCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *ContractCreate) SetNillableRemark(v *string) *ContractCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *ContractCreate) SetTenant(v *Tenant) *ContractCreate {
	return _c.SetTenantID(v.ID)
}

// Mutation returns the ContractMutation object of the builder.
func (_c *ContractCreate) Mutation() *ContractMutation {
	return _c.mutation
}

// Save creates the Contract in the database.
func (_c *ContractCreate) Save(ctx context.Context) (*Contract, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContractCreate) SaveX(ctx context.Context) *Contract {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContractCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContractCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContractCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := contract.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := contract.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.PartyA(); !ok {
		v := contract.DefaultPartyA
		_c.mutation.SetPartyA(v)
	}
	if _, ok := _c.mutation.PartyB(); !ok {
		v := contract.DefaultPartyB
		_c.mutation.SetPartyB(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := contract.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		v := contract.DefaultStartDate()
		_c.mutation.SetStartDate(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := contract.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.FileURL(); !ok {
		v := contract.DefaultFileURL
		_c.mutation.SetFileURL(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := contract.DefaultRemark
		_c.mutation.SetRemark(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContractCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Contract.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Contract.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Contract.tenant_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Contract.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := contract.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Contract.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PartyA(); !ok {
		return &ValidationError{Name: "party_a", err: errors.New(`ent: missing required field "Contract.party_a"`)}
	}
	if _, ok := _c.mutation.PartyB(); !ok {
		return &ValidationError{Name: "party_b", err: errors.New(`ent: missing required field "Contract.party_b"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Contract.amount"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "Contract.start_date"`)}
	}
	if _, ok := _c.mutation.EndDate(); !ok {
		return &ValidationError{Name: "end_date", err: errors.New(`ent: missing required field "Contract.end_date"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Contract.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := contract.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Contract.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileURL(); !ok {
		return &ValidationError{Name: "file_url", err: errors.New(`ent: missing required field "Contract.file_url"`)}
	}
	if _, ok := _c.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New(`ent: missing required field "Contract.remark"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Contract.tenant"`)}
	}
	return nil
}

func (_c *ContractCreate) sqlSave(ctx context.Context) (*Contract, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContractCreate) createSpec() (*Contract, *sqlgraph.CreateSpec) {
	var (
		_node = &Contract{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contract.Table, sqlgraph.NewFieldSpec(contract.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(contract.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(contract.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(contract.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.PartyA(); ok {
		_spec.SetField(contract.FieldPartyA, field.TypeString, value)
		_node.PartyA = value
	}
	if value, ok := _c.mutation.PartyB(); ok {
		_spec.SetField(contract.FieldPartyB, field.TypeString, value)
		_node.PartyB = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(contract.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(contract.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(contract.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(contract.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.FileURL(); ok {
		_spec.SetField(contract.FieldFileURL, field.TypeString, value)
		_node.FileURL = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(contract.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contract.TenantTable,
			Columns: []string{contract.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ContractCreateBulk is the builder for creating many Contract entities in bulk.
type ContractCreateBulk struct {
	config
	err      error
	builders []*ContractCreate
}

// Save creates the Contract entities in the database.
func (_c *ContractCreateBulk) Save(ctx context.Context) ([]*Contract, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Contract, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContractMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContractCreateBulk) SaveX(ctx context.Context) []*Contract {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContractCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContractCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
