// Code generated by ent, DO NOT EDIT.

package ent

import (
	"starledger/ent/auditlog"
	"starledger/ent/bill"
	"starledger/ent/contract"
	"starledger/ent/invoice"
	"starledger/ent/role"
	"starledger/ent/schema"
	"starledger/ent/serverlease"
	"starledger/ent/task"
	"starledger/ent/tenant"
	"starledger/ent/tenantmodule"
	"starledger/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogMixin := schema.AuditLog{}.Mixin()
	auditlogMixinFields0 := auditlogMixin[0].Fields()
	_ = auditlogMixinFields0
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogMixinFields0[0].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	// auditlogDescUpdatedAt is the schema descriptor for updated_at field.
	auditlogDescUpdatedAt := auditlogMixinFields0[1].Descriptor()
	// auditlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	auditlog.DefaultUpdatedAt = auditlogDescUpdatedAt.Default.(func() time.Time)
	// auditlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	auditlog.UpdateDefaultUpdatedAt = auditlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// auditlogDescUserID is the schema descriptor for user_id field.
	auditlogDescUserID := auditlogFields[1].Descriptor()
	// auditlog.DefaultUserID holds the default value on creation for the user_id field.
	auditlog.DefaultUserID = auditlogDescUserID.Default.(int)
	// auditlogDescUsername is the schema descriptor for username field.
	auditlogDescUsername := auditlogFields[2].Descriptor()
	// auditlog.DefaultUsername holds the default value on creation for the username field.
	auditlog.DefaultUsername = auditlogDescUsername.Default.(string)
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[3].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescResourceType is the schema descriptor for resource_type field.
	auditlogDescResourceType := auditlogFields[4].Descriptor()
	// auditlog.DefaultResourceType holds the default value on creation for the resource_type field.
	auditlog.DefaultResourceType = auditlogDescResourceType.Default.(string)
	// auditlogDescResourceID is the schema descriptor for resource_id field.
	auditlogDescResourceID := auditlogFields[5].Descriptor()
	// auditlog.DefaultResourceID holds the default value on creation for the resource_id field.
	auditlog.DefaultResourceID = auditlogDescResourceID.Default.(int)
	// auditlogDescDetail is the schema descriptor for detail field.
	auditlogDescDetail := auditlogFields[6].Descriptor()
	// auditlog.DefaultDetail holds the default value on creation for the detail field.
	auditlog.DefaultDetail = auditlogDescDetail.Default.(string)
	// auditlogDescIPAddress is the schema descriptor for ip_address field.
	auditlogDescIPAddress := auditlogFields[7].Descriptor()
	// auditlog.DefaultIPAddress holds the default value on creation for the ip_address field.
	auditlog.DefaultIPAddress = auditlogDescIPAddress.Default.(string)
	// auditlogDescUserAgent is the schema descriptor for user_agent field.
	auditlogDescUserAgent := auditlogFields[8].Descriptor()
	// auditlog.DefaultUserAgent holds the default value on creation for the user_agent field.
	auditlog.DefaultUserAgent = auditlogDescUserAgent.Default.(string)
	// auditlogDescStatus is the schema descriptor for status field.
	auditlogDescStatus := auditlogFields[9].Descriptor()
	// auditlog.DefaultStatus holds the default value on creation for the status field.
	auditlog.DefaultStatus = auditlogDescStatus.Default.(string)
	billMixin := schema.Bill{}.Mixin()
	billMixinFields0 := billMixin[0].Fields()
	_ = billMixinFields0
	billFields := schema.Bill{}.Fields()
	_ = billFields
	// billDescCreatedAt is the schema descriptor for created_at field.
	billDescCreatedAt := billMixinFields0[0].Descriptor()
	// bill.DefaultCreatedAt holds the default value on creation for the created_at field.
	bill.DefaultCreatedAt = billDescCreatedAt.Default.(func() time.Time)
	// billDescUpdatedAt is the schema descriptor for updated_at field.
	billDescUpdatedAt := billMixinFields0[1].Descriptor()
	// bill.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bill.DefaultUpdatedAt = billDescUpdatedAt.Default.(func() time.Time)
	// bill.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bill.UpdateDefaultUpdatedAt = billDescUpdatedAt.UpdateDefault.(func() time.Time)
	// billDescBillNo is the schema descriptor for bill_no field.
	billDescBillNo := billFields[1].Descriptor()
	// bill.BillNoValidator is a validator for the "bill_no" field. It is called by the builders before save.
	bill.BillNoValidator = billDescBillNo.Validators[0].(func(string) error)
	// billDescBillType is the schema descriptor for bill_type field.
	billDescBillType := billFields[2].Descriptor()
	// bill.BillTypeValidator is a validator for the "bill_type" field. It is called by the builders before save.
	bill.BillTypeValidator = billDescBillType.Validators[0].(func(string) error)
	// billDescAmount is the schema descriptor for amount field.
	billDescAmount := billFields[4].Descriptor()
	// bill.DefaultAmount holds the default value on creation for the amount field.
	bill.DefaultAmount = billDescAmount.Default.(float64)
	// billDescBillDate is the schema descriptor for bill_date field.
	billDescBillDate := billFields[5].Descriptor()
	// bill.DefaultBillDate holds the default value on creation for the bill_date field.
	bill.DefaultBillDate = billDescBillDate.Default.(func() time.Time)
	// billDescPaymentMethod is the schema descriptor for payment_method field.
	billDescPaymentMethod := billFields[9].Descriptor()
	// bill.DefaultPaymentMethod holds the default value on creation for the payment_method field.
	bill.DefaultPaymentMethod = billDescPaymentMethod.Default.(string)
	// billDescInvoiceNo is the schema descriptor for invoice_no field.
	billDescInvoiceNo := billFields[10].Descriptor()
	// bill.DefaultInvoiceNo holds the default value on creation for the invoice_no field.
	bill.DefaultInvoiceNo = billDescInvoiceNo.Default.(string)
	// billDescRemark is the schema descriptor for remark field.
	billDescRemark := billFields[11].Descriptor()
	// bill.DefaultRemark holds the default value on creation for the remark field.
	bill.DefaultRemark = billDescRemark.Default.(string)
	contractMixin := schema.Contract{}.Mixin()
	contractMixinFields0 := contractMixin[0].Fields()
	_ = contractMixinFields0
	contractFields := schema.Contract{}.Fields()
	_ = contractFields
	// contractDescCreatedAt is the schema descriptor for created_at field.
	contractDescCreatedAt := contractMixinFields0[0].Descriptor()
	// contract.DefaultCreatedAt holds the default value on creation for the created_at field.
	contract.DefaultCreatedAt = contractDescCreatedAt.Default.(func() time.Time)
	// contractDescUpdatedAt is the schema descriptor for updated_at field.
	contractDescUpdatedAt := contractMixinFields0[1].Descriptor()
	// contract.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	contract.DefaultUpdatedAt = contractDescUpdatedAt.Default.(func() time.Time)
	// contract.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	contract.UpdateDefaultUpdatedAt = contractDescUpdatedAt.UpdateDefault.(func() time.Time)
	// contractDescTitle is the schema descriptor for title field.
	contractDescTitle := contractFields[1].Descriptor()
	// contract.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	contract.TitleValidator = contractDescTitle.Validators[0].(func(string) error)
	// contractDescPartyA is the schema descriptor for party_a field.
	contractDescPartyA := contractFields[2].Descriptor()
	// contract.DefaultPartyA holds the default value on creation for the party_a field.
	contract.DefaultPartyA = contractDescPartyA.Default.(string)
	// contractDescPartyB is the schema descriptor for party_b field.
	contractDescPartyB := contractFields[3].Descriptor()
	// contract.DefaultPartyB holds the default value on creation for the party_b field.
	contract.DefaultPartyB = contractDescPartyB.Default.(string)
	// contractDescAmount is the schema descriptor for amount field.
	contractDescAmount := contractFields[4].Descriptor()
	// contract.DefaultAmount holds the default value on creation for the amount field.
	contract.DefaultAmount = contractDescAmount.Default.(float64)
	// contractDescStartDate is the schema descriptor for start_date field.
	contractDescStartDate := contractFields[5].Descriptor()
	// contract.DefaultStartDate holds the default value on creation for the start_date field.
	contract.DefaultStartDate = contractDescStartDate.Default.(func() time.Time)
	// contractDescFileURL is the schema descriptor for file_url field.
	contractDescFileURL := contractFields[8].Descriptor()
	// contract.DefaultFileURL holds the default value on creation for the file_url field.
	contract.DefaultFileURL = contractDescFileURL.Default.(string)
	// contractDescRemark is the schema descriptor for remark field.
	contractDescRemark := contractFields[9].Descriptor()
	// contract.DefaultRemark holds the default value on creation for the remark field.
	contract.DefaultRemark = contractDescRemark.Default.(string)
	invoiceMixin := schema.Invoice{}.Mixin()
	invoiceMixinFields0 := invoiceMixin[0].Fields()
	_ = invoiceMixinFields0
	invoiceFields := schema.Invoice{}.Fields()
	_ = invoiceFields
	// invoiceDescCreatedAt is the schema descriptor for created_at field.
	invoiceDescCreatedAt := invoiceMixinFields0[0].Descriptor()
	// invoice.DefaultCreatedAt holds the default value on creation for the created_at field.
	invoice.DefaultCreatedAt = invoiceDescCreatedAt.Default.(func() time.Time)
	// invoiceDescUpdatedAt is the schema descriptor for updated_at field.
	invoiceDescUpdatedAt := invoiceMixinFields0[1].Descriptor()
	// invoice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	invoice.DefaultUpdatedAt = invoiceDescUpdatedAt.Default.(func() time.Time)
	// invoice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	invoice.UpdateDefaultUpdatedAt = invoiceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// invoiceDescInvoiceNo is the schema descriptor for invoice_no field.
	invoiceDescInvoiceNo := invoiceFields[2].Descriptor()
	// invoice.InvoiceNoValidator is a validator for the "invoice_no" field. It is called by the builders before save.
	invoice.InvoiceNoValidator = invoiceDescInvoiceNo.Validators[0].(func(string) error)
	// invoiceDescInvoiceCode is the schema descriptor for invoice_code field.
	invoiceDescInvoiceCode := invoiceFields[3].Descriptor()
	// invoice.DefaultInvoiceCode holds the default value on creation for the invoice_code field.
	invoice.DefaultInvoiceCode = invoiceDescInvoiceCode.Default.(string)
	// invoiceDescAmount is the schema descriptor for amount field.
	invoiceDescAmount := invoiceFields[5].Descriptor()
	// invoice.DefaultAmount holds the default value on creation for the amount field.
	invoice.DefaultAmount = invoiceDescAmount.Default.(float64)
	// invoiceDescTaxAmount is the schema descriptor for tax_amount field.
	invoiceDescTaxAmount := invoiceFields[6].Descriptor()
	// invoice.DefaultTaxAmount holds the default value on creation for the tax_amount field.
	invoice.DefaultTaxAmount = invoiceDescTaxAmount.Default.(float64)
	// invoiceDescTotalAmount is the schema descriptor for total_amount field.
	invoiceDescTotalAmount := invoiceFields[7].Descriptor()
	// invoice.DefaultTotalAmount holds the default value on creation for the total_amount field.
	invoice.DefaultTotalAmount = invoiceDescTotalAmount.Default.(float64)
	// invoiceDescTaxRate is the schema descriptor for tax_rate field.
	invoiceDescTaxRate := invoiceFields[8].Descriptor()
	// invoice.DefaultTaxRate holds the default value on creation for the tax_rate field.
	invoice.DefaultTaxRate = invoiceDescTaxRate.Default.(float64)
	// invoiceDescBuyerName is the schema descriptor for buyer_name field.
	invoiceDescBuyerName := invoiceFields[9].Descriptor()
	// invoice.DefaultBuyerName holds the default value on creation for the buyer_name field.
	invoice.DefaultBuyerName = invoiceDescBuyerName.Default.(string)
	// invoiceDescBuyerTaxNo is the schema descriptor for buyer_tax_no field.
	invoiceDescBuyerTaxNo := invoiceFields[10].Descriptor()
	// invoice.DefaultBuyerTaxNo holds the default value on creation for the buyer_tax_no field.
	invoice.DefaultBuyerTaxNo = invoiceDescBuyerTaxNo.Default.(string)
	// invoiceDescBuyerAddress is the schema descriptor for buyer_address field.
	invoiceDescBuyerAddress := invoiceFields[11].Descriptor()
	// invoice.DefaultBuyerAddress holds the default value on creation for the buyer_address field.
	invoice.DefaultBuyerAddress = invoiceDescBuyerAddress.Default.(string)
	// invoiceDescBuyerBank is the schema descriptor for buyer_bank field.
	invoiceDescBuyerBank := invoiceFields[12].Descriptor()
	// invoice.DefaultBuyerBank holds the default value on creation for the buyer_bank field.
	invoice.DefaultBuyerBank = invoiceDescBuyerBank.Default.(string)
	// invoiceDescSellerName is the schema descriptor for seller_name field.
	invoiceDescSellerName := invoiceFields[13].Descriptor()
	// invoice.DefaultSellerName holds the default value on creation for the seller_name field.
	invoice.DefaultSellerName = invoiceDescSellerName.Default.(string)
	// invoiceDescSellerTaxNo is the schema descriptor for seller_tax_no field.
	invoiceDescSellerTaxNo := invoiceFields[14].Descriptor()
	// invoice.DefaultSellerTaxNo holds the default value on creation for the seller_tax_no field.
	invoice.DefaultSellerTaxNo = invoiceDescSellerTaxNo.Default.(string)
	// invoiceDescSellerAddress is the schema descriptor for seller_address field.
	invoiceDescSellerAddress := invoiceFields[15].Descriptor()
	// invoice.DefaultSellerAddress holds the default value on creation for the seller_address field.
	invoice.DefaultSellerAddress = invoiceDescSellerAddress.Default.(string)
	// invoiceDescSellerBank is the schema descriptor for seller_bank field.
	invoiceDescSellerBank := invoiceFields[16].Descriptor()
	// invoice.DefaultSellerBank holds the default value on creation for the seller_bank field.
	invoice.DefaultSellerBank = invoiceDescSellerBank.Default.(string)
	// invoiceDescItemsDetail is the schema descriptor for items_detail field.
	invoiceDescItemsDetail := invoiceFields[19].Descriptor()
	// invoice.DefaultItemsDetail holds the default value on creation for the items_detail field.
	invoice.DefaultItemsDetail = invoiceDescItemsDetail.Default.(string)
	// invoiceDescRemark is the schema descriptor for remark field.
	invoiceDescRemark := invoiceFields[20].Descriptor()
	// invoice.DefaultRemark holds the default value on creation for the remark field.
	invoice.DefaultRemark = invoiceDescRemark.Default.(string)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[0].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[1].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[3].Descriptor()
	// role.DefaultDescription holds the default value on creation for the description field.
	role.DefaultDescription = roleDescDescription.Default.(string)
	serverleaseMixin := schema.ServerLease{}.Mixin()
	serverleaseMixinFields0 := serverleaseMixin[0].Fields()
	_ = serverleaseMixinFields0
	serverleaseFields := schema.ServerLease{}.Fields()
	_ = serverleaseFields
	// serverleaseDescCreatedAt is the schema descriptor for created_at field.
	serverleaseDescCreatedAt := serverleaseMixinFields0[0].Descriptor()
	// serverlease.DefaultCreatedAt holds the default value on creation for the created_at field.
	serverlease.DefaultCreatedAt = serverleaseDescCreatedAt.Default.(func() time.Time)
	// serverleaseDescUpdatedAt is the schema descriptor for updated_at field.
	serverleaseDescUpdatedAt := serverleaseMixinFields0[1].Descriptor()
	// serverlease.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	serverlease.DefaultUpdatedAt = serverleaseDescUpdatedAt.Default.(func() time.Time)
	// serverlease.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	serverlease.UpdateDefaultUpdatedAt = serverleaseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// serverleaseDescServerName is the schema descriptor for server_name field.
	serverleaseDescServerName := serverleaseFields[1].Descriptor()
	// serverlease.ServerNameValidator is a validator for the "server_name" field. It is called by the builders before save.
	serverlease.ServerNameValidator = serverleaseDescServerName.Validators[0].(func(string) error)
	// serverleaseDescProvider is the schema descriptor for provider field.
	serverleaseDescProvider := serverleaseFields[2].Descriptor()
	// serverlease.DefaultProvider holds the default value on creation for the provider field.
	serverlease.DefaultProvider = serverleaseDescProvider.Default.(string)
	// serverleaseDescConfig is the schema descriptor for config field.
	serverleaseDescConfig := serverleaseFields[3].Descriptor()
	// serverlease.DefaultConfig holds the default value on creation for the config field.
	serverlease.DefaultConfig = serverleaseDescConfig.Default.(string)
	// serverleaseDescIPAddress is the schema descriptor for ip_address field.
	serverleaseDescIPAddress := serverleaseFields[4].Descriptor()
	// serverlease.DefaultIPAddress holds the default value on creation for the ip_address field.
	serverlease.DefaultIPAddress = serverleaseDescIPAddress.Default.(string)
	// serverleaseDescLocation is the schema descriptor for location field.
	serverleaseDescLocation := serverleaseFields[5].Descriptor()
	// serverlease.DefaultLocation holds the default value on creation for the location field.
	serverlease.DefaultLocation = serverleaseDescLocation.Default.(string)
	// serverleaseDescMonthlyCost is the schema descriptor for monthly_cost field.
	serverleaseDescMonthlyCost := serverleaseFields[6].Descriptor()
	// serverlease.DefaultMonthlyCost holds the default value on creation for the monthly_cost field.
	serverlease.DefaultMonthlyCost = serverleaseDescMonthlyCost.Default.(float64)
	// serverleaseDescStartDate is the schema descriptor for start_date field.
	serverleaseDescStartDate := serverleaseFields[7].Descriptor()
	// serverlease.DefaultStartDate holds the default value on creation for the start_date field.
	serverlease.DefaultStartDate = serverleaseDescStartDate.Default.(func() time.Time)
	// serverleaseDescContractNo is the schema descriptor for contract_no field.
	serverleaseDescContractNo := serverleaseFields[11].Descriptor()
	// serverlease.DefaultContractNo holds the default value on creation for the contract_no field.
	serverlease.DefaultContractNo = serverleaseDescContractNo.Default.(string)
	// serverleaseDescRemark is the schema descriptor for remark field.
	serverleaseDescRemark := serverleaseFields[12].Descriptor()
	// serverlease.DefaultRemark holds the default value on creation for the remark field.
	serverlease.DefaultRemark = serverleaseDescRemark.Default.(string)
	taskMixin := schema.Task{}.Mixin()
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskMixinFields0[0].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskMixinFields0[1].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	// taskDescTitle is the schema descriptor for title field.
	taskDescTitle := taskFields[1].Descriptor()
	// task.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	task.TitleValidator = taskDescTitle.Validators[0].(func(string) error)
	// taskDescDescription is the schema descriptor for description field.
	taskDescDescription := taskFields[2].Descriptor()
	// task.DefaultDescription holds the default value on creation for the description field.
	task.DefaultDescription = taskDescDescription.Default.(string)
	tenantMixin := schema.Tenant{}.Mixin()
	tenantMixinFields0 := tenantMixin[0].Fields()
	_ = tenantMixinFields0
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantMixinFields0[0].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantMixinFields0[1].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[0].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescContact is the schema descriptor for contact field.
	tenantDescContact := tenantFields[2].Descriptor()
	// tenant.DefaultContact holds the default value on creation for the contact field.
	tenant.DefaultContact = tenantDescContact.Default.(string)
	// tenantDescPhone is the schema descriptor for phone field.
	tenantDescPhone := tenantFields[3].Descriptor()
	// tenant.DefaultPhone holds the default value on creation for the phone field.
	tenant.DefaultPhone = tenantDescPhone.Default.(string)
	// tenantDescEmail is the schema descriptor for email field.
	tenantDescEmail := tenantFields[4].Descriptor()
	// tenant.DefaultEmail holds the default value on creation for the email field.
	tenant.DefaultEmail = tenantDescEmail.Default.(string)
	tenantmoduleMixin := schema.TenantModule{}.Mixin()
	tenantmoduleMixinFields0 := tenantmoduleMixin[0].Fields()
	_ = tenantmoduleMixinFields0
	tenantmoduleFields := schema.TenantModule{}.Fields()
	_ = tenantmoduleFields
	// tenantmoduleDescCreatedAt is the schema descriptor for created_at field.
	tenantmoduleDescCreatedAt := tenantmoduleMixinFields0[0].Descriptor()
	// tenantmodule.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantmodule.DefaultCreatedAt = tenantmoduleDescCreatedAt.Default.(func() time.Time)
	// tenantmoduleDescUpdatedAt is the schema descriptor for updated_at field.
	tenantmoduleDescUpdatedAt := tenantmoduleMixinFields0[1].Descriptor()
	// tenantmodule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenantmodule.DefaultUpdatedAt = tenantmoduleDescUpdatedAt.Default.(func() time.Time)
	// tenantmodule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenantmodule.UpdateDefaultUpdatedAt = tenantmoduleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantmoduleDescModuleName is the schema descriptor for module_name field.
	tenantmoduleDescModuleName := tenantmoduleFields[1].Descriptor()
	// tenantmodule.ModuleNameValidator is a validator for the "module_name" field. It is called by the builders before save.
	tenantmodule.ModuleNameValidator = tenantmoduleDescModuleName.Validators[0].(func(string) error)
	// tenantmoduleDescEnabled is the schema descriptor for enabled field.
	tenantmoduleDescEnabled := tenantmoduleFields[2].Descriptor()
	// tenantmodule.DefaultEnabled holds the default value on creation for the enabled field.
	tenantmodule.DefaultEnabled = tenantmoduleDescEnabled.Default.(bool)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescRealName is the schema descriptor for real_name field.
	userDescRealName := userFields[3].Descriptor()
	// user.DefaultRealName holds the default value on creation for the real_name field.
	user.DefaultRealName = userDescRealName.Default.(string)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[5].Descriptor()
	// user.DefaultPhone holds the default value on creation for the phone field.
	user.DefaultPhone = userDescPhone.Default.(string)
}
