// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"starledger/ent/bill"
	"starledger/ent/predicate"
	"starledger/ent/serverlease"
	"starledger/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerLeaseUpdate is the builder for updating ServerLease entities.
type ServerLeaseUpdate struct {
	config
	hooks    []Hook
	mutation *ServerLeaseMutation
}

// Where appends a list predicates to the ServerLeaseUpdate builder.
func (_u *ServerLeaseUpdate) Where(ps ...predicate.ServerLease) *ServerLeaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServerLeaseUpdate) SetUpdatedAt(v time.Time) *ServerLeaseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ServerLeaseUpdate) SetTenantID(v int) *ServerLeaseUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableTenantID(v *int) *ServerLeaseUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetServerName sets the "server_name" field.
func (_u *ServerLeaseUpdate) SetServerName(v string) *ServerLeaseUpdate {
	_u.mutation.SetServerName(v)
	return _u
}

// SetNillableServerName sets the "server_name" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableServerName(v *string) *ServerLeaseUpdate {
	if v != nil {
		_u.SetServerName(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ServerLeaseUpdate) SetProvider(v string) *ServerLeaseUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableProvider(v *string) *ServerLeaseUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ServerLeaseUpdate) SetConfig(v string) *ServerLeaseUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableConfig(v *string) *ServerLeaseUpdate {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *ServerLeaseUpdate) SetIPAddress(v string) *ServerLeaseUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableIPAddress(v *string) *ServerLeaseUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *ServerLeaseUpdate) SetLocation(v string) *ServerLeaseUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableLocation(v *string) *ServerLeaseUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetMonthlyCost sets the "monthly_cost" field.
func (_u *ServerLeaseUpdate) SetMonthlyCost(v float64) *ServerLeaseUpdate {
	_u.mutation.ResetMonthlyCost()
	_u.mutation.SetMonthlyCost(v)
	return _u
}

// SetNillableMonthlyCost sets the "monthly_cost" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableMonthlyCost(v *float64) *ServerLeaseUpdate {
	if v != nil {
		_u.SetMonthlyCost(*v)
	}
	return _u
}

// AddMonthlyCost adds value to the "monthly_cost" field.
func (_u *ServerLeaseUpdate) AddMonthlyCost(v float64) *ServerLeaseUpdate {
	_u.mutation.AddMonthlyCost(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ServerLeaseUpdate) SetStartDate(v time.Time) *ServerLeaseUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableStartDate(v *time.Time) *ServerLeaseUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ServerLeaseUpdate) SetEndDate(v time.Time) *ServerLeaseUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableEndDate(v *time.Time) *ServerLeaseUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetRenewCycle sets the "renew_cycle" field.
func (_u *ServerLeaseUpdate) SetRenewCycle(v serverlease.RenewCycle) *ServerLeaseUpdate {
	_u.mutation.SetRenewCycle(v)
	return _u
}

// SetNillableRenewCycle sets the "renew_cycle" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableRenewCycle(v *serverlease.RenewCycle) *ServerLeaseUpdate {
	if v != nil {
		_u.SetRenewCycle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ServerLeaseUpdate) SetStatus(v serverlease.Status) *ServerLeaseUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableStatus(v *serverlease.Status) *ServerLeaseUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetContractNo sets the "contract_no" field.
func (_u *ServerLeaseUpdate) SetContractNo(v string) *ServerLeaseUpdate {
	_u.mutation.SetContractNo(v)
	return _u
}

// SetNillableContractNo sets the "contract_no" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableContractNo(v *string) *ServerLeaseUpdate {
	if v != nil {
		_u.SetContractNo(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ServerLeaseUpdate) SetRemark(v string) *ServerLeaseUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ServerLeaseUpdate) SetNillableRemark(v *string) *ServerLeaseUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *ServerLeaseUpdate) SetTenant(v *Tenant) *ServerLeaseUpdate {
	return _u.SetTenantID(v.ID)
}

// AddBillIDs adds the "bills" edge to the Bill entity by IDs.
func (_u *ServerLeaseUpdate) AddBillIDs(ids ...int) *ServerLeaseUpdate {
	_u.mutation.AddBillIDs(ids...)
	return _u
}

// AddBills adds the "bills" edges to the Bill entity.
func (_u *ServerLeaseUpdate) AddBills(v ...*Bill) *ServerLeaseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBillIDs(ids...)
}

// Mutation returns the ServerLeaseMutation object of the builder.
func (_u *ServerLeaseUpdate) Mutation() *ServerLeaseMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *ServerLeaseUpdate) ClearTenant() *ServerLeaseUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearBills clears all "bills" edges to the Bill entity.
func (_u *ServerLeaseUpdate) ClearBills() *ServerLeaseUpdate {
	_u.mutation.ClearBills()
	return _u
}

// RemoveBillIDs removes the "bills" edge to Bill entities by IDs.
func (_u *ServerLeaseUpdate) RemoveBillIDs(ids ...int) *ServerLeaseUpdate {
	_u.mutation.RemoveBillIDs(ids...)
	return _u
}

// RemoveBills removes "bills" edges to Bill entities.
func (_u *ServerLeaseUpdate) RemoveBills(v ...*Bill) *ServerLeaseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBillIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServerLeaseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServerLeaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServerLeaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServerLeaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServerLeaseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := serverlease.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServerLeaseUpdate) check() error {
	if v, ok := _u.mutation.ServerName(); ok {
		if err := serverlease.ServerNameValidator(v); err != nil {
			return &ValidationError{Name: "server_name", err: fmt.Errorf(`ent: validator failed for field "ServerLease.server_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RenewCycle(); ok {
		if err := serverlease.RenewCycleValidator(v); err != nil {
			return &ValidationError{Name: "renew_cycle", err: fmt.Errorf(`ent: validator failed for field "ServerLease.renew_cycle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := serverlease.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ServerLease.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServerLease.tenant"`)
	}
	return nil
}

func (_u *ServerLeaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serverlease.Table, serverlease.Columns, sqlgraph.NewFieldSpec(serverlease.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(serverlease.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ServerName(); ok {
		_spec.SetField(serverlease.FieldServerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(serverlease.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(serverlease.FieldConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(serverlease.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(serverlease.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.MonthlyCost(); ok {
		_spec.SetField(serverlease.FieldMonthlyCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyCost(); ok {
		_spec.AddField(serverlease.FieldMonthlyCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(serverlease.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(serverlease.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RenewCycle(); ok {
		_spec.SetField(serverlease.FieldRenewCycle, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(serverlease.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ContractNo(); ok {
		_spec.SetField(serverlease.FieldContractNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(serverlease.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serverlease.TenantTable,
			Columns: []string{serverlease.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serverlease.TenantTable,
			Columns: []string{serverlease.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serverlease.BillsTable,
			Columns: []string{serverlease.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBillsIDs(); len(nodes) > 0 && !_u.mutation.BillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serverlease.BillsTable,
			Columns: []string{serverlease.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serverlease.BillsTable,
			Columns: []string{serverlease.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serverlease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServerLeaseUpdateOne is the builder for updating a single ServerLease entity.
type ServerLeaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServerLeaseMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServerLeaseUpdateOne) SetUpdatedAt(v time.Time) *ServerLeaseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ServerLeaseUpdateOne) SetTenantID(v int) *ServerLeaseUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableTenantID(v *int) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetServerName sets the "server_name" field.
func (_u *ServerLeaseUpdateOne) SetServerName(v string) *ServerLeaseUpdateOne {
	_u.mutation.SetServerName(v)
	return _u
}

// SetNillableServerName sets the "server_name" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableServerName(v *string) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetServerName(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ServerLeaseUpdateOne) SetProvider(v string) *ServerLeaseUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableProvider(v *string) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ServerLeaseUpdateOne) SetConfig(v string) *ServerLeaseUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableConfig(v *string) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *ServerLeaseUpdateOne) SetIPAddress(v string) *ServerLeaseUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableIPAddress(v *string) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *ServerLeaseUpdateOne) SetLocation(v string) *ServerLeaseUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableLocation(v *string) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetMonthlyCost sets the "monthly_cost" field.
func (_u *ServerLeaseUpdateOne) SetMonthlyCost(v float64) *ServerLeaseUpdateOne {
	_u.mutation.ResetMonthlyCost()
	_u.mutation.SetMonthlyCost(v)
	return _u
}

// SetNillableMonthlyCost sets the "monthly_cost" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableMonthlyCost(v *float64) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetMonthlyCost(*v)
	}
	return _u
}

// AddMonthlyCost adds value to the "monthly_cost" field.
func (_u *ServerLeaseUpdateOne) AddMonthlyCost(v float64) *ServerLeaseUpdateOne {
	_u.mutation.AddMonthlyCost(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ServerLeaseUpdateOne) SetStartDate(v time.Time) *ServerLeaseUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableStartDate(v *time.Time) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ServerLeaseUpdateOne) SetEndDate(v time.Time) *ServerLeaseUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableEndDate(v *time.Time) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetRenewCycle sets the "renew_cycle" field.
func (_u *ServerLeaseUpdateOne) SetRenewCycle(v serverlease.RenewCycle) *ServerLeaseUpdateOne {
	_u.mutation.SetRenewCycle(v)
	return _u
}

// SetNillableRenewCycle sets the "renew_cycle" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableRenewCycle(v *serverlease.RenewCycle) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetRenewCycle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ServerLeaseUpdateOne) SetStatus(v serverlease.Status) *ServerLeaseUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableStatus(v *serverlease.Status) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetContractNo sets the "contract_no" field.
func (_u *ServerLeaseUpdateOne) SetContractNo(v string) *ServerLeaseUpdateOne {
	_u.mutation.SetContractNo(v)
	return _u
}

// SetNillableContractNo sets the "contract_no" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableContractNo(v *string) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetContractNo(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ServerLeaseUpdateOne) SetRemark(v string) *ServerLeaseUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ServerLeaseUpdateOne) SetNillableRemark(v *string) *ServerLeaseUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *ServerLeaseUpdateOne) SetTenant(v *Tenant) *ServerLeaseUpdateOne {
	return _u.SetTenantID(v.ID)
}

// AddBillIDs adds the "bills" edge to the Bill entity by IDs.
func (_u *ServerLeaseUpdateOne) AddBillIDs(ids ...int) *ServerLeaseUpdateOne {
	_u.mutation.AddBillIDs(ids...)
	return _u
}

// AddBills adds the "bills" edges to the Bill entity.
func (_u *ServerLeaseUpdateOne) AddBills(v ...*Bill) *ServerLeaseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBillIDs(ids...)
}

// Mutation returns the ServerLeaseMutation object of the builder.
func (_u *ServerLeaseUpdateOne) Mutation() *ServerLeaseMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *ServerLeaseUpdateOne) ClearTenant() *ServerLeaseUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearBills clears all "bills" edges to the Bill entity.
func (_u *ServerLeaseUpdateOne) ClearBills() *ServerLeaseUpdateOne {
	_u.mutation.ClearBills()
	return _u
}

// RemoveBillIDs removes the "bills" edge to Bill entities by IDs.
func (_u *ServerLeaseUpdateOne) RemoveBillIDs(ids ...int) *ServerLeaseUpdateOne {
	_u.mutation.RemoveBillIDs(ids...)
	return _u
}

// RemoveBills removes "bills" edges to Bill entities.
func (_u *ServerLeaseUpdateOne) RemoveBills(v ...*Bill) *ServerLeaseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBillIDs(ids...)
}

// Where appends a list predicates to the ServerLeaseUpdate builder.
func (_u *ServerLeaseUpdateOne) Where(ps ...predicate.ServerLease) *ServerLeaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServerLeaseUpdateOne) Select(field string, fields ...string) *ServerLeaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServerLease entity.
func (_u *ServerLeaseUpdateOne) Save(ctx context.Context) (*ServerLease, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServerLeaseUpdateOne) SaveX(ctx context.Context) *ServerLease {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServerLeaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServerLeaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServerLeaseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := serverlease.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServerLeaseUpdateOne) check() error {
	if v, ok := _u.mutation.ServerName(); ok {
		if err := serverlease.ServerNameValidator(v); err != nil {
			return &ValidationError{Name: "server_name", err: fmt.Errorf(`ent: validator failed for field "ServerLease.server_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RenewCycle(); ok {
		if err := serverlease.RenewCycleValidator(v); err != nil {
			return &ValidationError{Name: "renew_cycle", err: fmt.Errorf(`ent: validator failed for field "ServerLease.renew_cycle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := serverlease.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ServerLease.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServerLease.tenant"`)
	}
	return nil
}

func (_u *ServerLeaseUpdateOne) sqlSave(ctx context.Context) (_node *ServerLease, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serverlease.Table, serverlease.Columns, sqlgraph.NewFieldSpec(serverlease.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServerLease.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serverlease.FieldID)
		for _, f := range fields {
			if !serverlease.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != serverlease.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(serverlease.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ServerName(); ok {
		_spec.SetField(serverlease.FieldServerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(serverlease.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(serverlease.FieldConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(serverlease.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(serverlease.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.MonthlyCost(); ok {
		_spec.SetField(serverlease.FieldMonthlyCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyCost(); ok {
		_spec.AddField(serverlease.FieldMonthlyCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(serverlease.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(serverlease.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RenewCycle(); ok {
		_spec.SetField(serverlease.FieldRenewCycle, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(serverlease.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ContractNo(); ok {
		_spec.SetField(serverlease.FieldContractNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(serverlease.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serverlease.TenantTable,
			Columns: []string{serverlease.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serverlease.TenantTable,
			Columns: []string{serverlease.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serverlease.BillsTable,
			Columns: []string{serverlease.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBillsIDs(); len(nodes) > 0 && !_u.mutation.BillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serverlease.BillsTable,
			Columns: []string{serverlease.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serverlease.BillsTable,
			Columns: []string{serverlease.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ServerLease{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serverlease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
