// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"starledger/ent/bill"
	"starledger/ent/serverlease"
	"starledger/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerLeaseCreate is the builder for creating a ServerLease entity.
type ServerLeaseCreate struct {
	config
	mutation *ServerLeaseMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ServerLeaseCreate) SetCreatedAt(v time.Time) *ServerLeaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableCreatedAt(v *time.Time) *ServerLeaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ServerLeaseCreate) SetUpdatedAt(v time.Time) *ServerLeaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableUpdatedAt(v *time.Time) *ServerLeaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ServerLeaseCreate) SetTenantID(v int) *ServerLeaseCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetServerName sets the "server_name" field.
func (_c *ServerLeaseCreate) SetServerName(v string) *ServerLeaseCreate {
	_c.mutation.SetServerName(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ServerLeaseCreate) SetProvider(v string) *ServerLeaseCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableProvider(v *string) *ServerLeaseCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *ServerLeaseCreate) SetConfig(v string) *ServerLeaseCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableConfig(v *string) *ServerLeaseCreate {
	if v != nil {
		_c.SetConfig(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *ServerLeaseCreate) SetIPAddress(v string) *ServerLeaseCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableIPAddress(v *string) *ServerLeaseCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *ServerLeaseCreate) SetLocation(v string) *ServerLeaseCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableLocation(v *string) *ServerLeaseCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetMonthlyCost sets the "monthly_cost" field.
func (_c *ServerLeaseCreate) SetMonthlyCost(v float64) *ServerLeaseCreate {
	_c.mutation.SetMonthlyCost(v)
	return _c
}

// SetNillableMonthlyCost sets the "monthly_cost" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableMonthlyCost(v *float64) *ServerLeaseCreate {
	if v != nil {
		_c.SetMonthlyCost(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *ServerLeaseCreate) SetStartDate(v time.Time) *ServerLeaseCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableStartDate(v *time.Time) *ServerLeaseCreate {
	if v != nil {
		_c.SetStartDate(*v)
	}
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *ServerLeaseCreate) SetEndDate(v time.Time) *ServerLeaseCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetRenewCycle sets the "renew_cycle" field.
func (_c *ServerLeaseCreate) SetRenewCycle(v serverlease.RenewCycle) *ServerLeaseCreate {
	_c.mutation.SetRenewCycle(v)
	return _c
}

// SetNillableRenewCycle sets the "renew_cycle" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableRenewCycle(v *serverlease.RenewCycle) *ServerLeaseCreate {
	if v != nil {
		_c.SetRenewCycle(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ServerLeaseCreate) SetStatus(v serverlease.Status) *ServerLeaseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableStatus(v *serverlease.Status) *ServerLeaseCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetContractNo sets the "contract_no" field.
func (_c *ServerLeaseCreate) SetContractNo(v string) *ServerLeaseCreate {
	_c.mutation.SetContractNo(v)
	return _c
}

// SetNillableContractNo sets the "contract_no" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableContractNo(v *string) *ServerLeaseCreate {
	if v != nil {
		_c.SetContractNo(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *ServerLeaseCreate) SetRemark(v string) *ServerLeaseCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *ServerLeaseCreate) SetNillableRemark(v *string) *ServerLeaseCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *ServerLeaseCreate) SetTenant(v *Tenant) *ServerLeaseCreate {
	return _c.SetTenantID(v.ID)
}

// AddBillIDs adds the "bills" edge to the Bill entity by IDs.
func (_c *ServerLeaseCreate) AddBillIDs(ids ...int) *ServerLeaseCreate {
	_c.mutation.AddBillIDs(ids...)
	return _c
}

// AddBills adds the "bills" edges to the Bill entity.
func (_c *ServerLeaseCreate) AddBills(v ...*Bill) *ServerLeaseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBillIDs(ids...)
}

// Mutation returns the ServerLeaseMutation object of the builder.
func (_c *ServerLeaseCreate) Mutation() *ServerLeaseMutation {
	return _c.mutation
}

// Save creates the ServerLease in the database.
func (_c *ServerLeaseCreate) Save(ctx context.Context) (*ServerLease, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ServerLeaseCreate) SaveX(ctx context.Context) *ServerLease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServerLeaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServerLeaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ServerLeaseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := serverlease.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := serverlease.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := serverlease.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Config(); !ok {
		v := serverlease.DefaultConfig
		_c.mutation.SetConfig(v)
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		v := serverlease.DefaultIPAddress
		_c.mutation.SetIPAddress(v)
	}
	if _, ok := _c.mutation.Location(); !ok {
		v := serverlease.DefaultLocation
		_c.mutation.SetLocation(v)
	}
	if _, ok := _c.mutation.MonthlyCost(); !ok {
		v := serverlease.DefaultMonthlyCost
		_c.mutation.SetMonthlyCost(v)
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		v := serverlease.DefaultStartDate()
		_c.mutation.SetStartDate(v)
	}
	if _, ok := _c.mutation.RenewCycle(); !ok {
		v := serverlease.DefaultRenewCycle
		_c.mutation.SetRenewCycle(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := serverlease.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ContractNo(); !ok {
		v := serverlease.DefaultContractNo
		_c.mutation.SetContractNo(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := serverlease.DefaultRemark
		_c.mutation.SetRemark(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ServerLeaseCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ServerLease.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ServerLease.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ServerLease.tenant_id"`)}
	}
	if _, ok := _c.mutation.ServerName(); !ok {
		return &ValidationError{Name: "server_name", err: errors.New(`ent: missing required field "ServerLease.server_name"`)}
	}
	if v, ok := _c.mutation.ServerName(); ok {
		if err := serverlease.ServerNameValidator(v); err != nil {
			return &ValidationError{Name: "server_name", err: fmt.Errorf(`ent: validator failed for field "ServerLease.server_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ServerLease.provider"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "ServerLease.config"`)}
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "ServerLease.ip_address"`)}
	}
	if _, ok := _c.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "ServerLease.location"`)}
	}
	if _, ok := _c.mutation.MonthlyCost(); !ok {
		return &ValidationError{Name: "monthly_cost", err: errors.New(`ent: missing required field "ServerLease.monthly_cost"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "ServerLease.start_date"`)}
	}
	if _, ok := _c.mutation.EndDate(); !ok {
		return &ValidationError{Name: "end_date", err: errors.New(`ent: missing required field "ServerLease.end_date"`)}
	}
	if _, ok := _c.mutation.RenewCycle(); !ok {
		return &ValidationError{Name: "renew_cycle", err: errors.New(`ent: missing required field "ServerLease.renew_cycle"`)}
	}
	if v, ok := _c.mutation.RenewCycle(); ok {
		if err := serverlease.RenewCycleValidator(v); err != nil {
			return &ValidationError{Name: "renew_cycle", err: fmt.Errorf(`ent: validator failed for field "ServerLease.renew_cycle": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ServerLease.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := serverlease.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ServerLease.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContractNo(); !ok {
		return &ValidationError{Name: "contract_no", err: errors.New(`ent: missing required field "ServerLease.contract_no"`)}
	}
	if _, ok := _c.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New(`ent: missing required field "ServerLease.remark"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "ServerLease.tenant"`)}
	}
	return nil
}

func (_c *ServerLeaseCreate) sqlSave(ctx context.Context) (*ServerLease, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ServerLeaseCreate) createSpec() (*ServerLease, *sqlgraph.CreateSpec) {
	var (
		_node = &ServerLease{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(serverlease.Table, sqlgraph.NewFieldSpec(serverlease.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(serverlease.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(serverlease.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ServerName(); ok {
		_spec.SetField(serverlease.FieldServerName, field.TypeString, value)
		_node.ServerName = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(serverlease.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(serverlease.FieldConfig, field.TypeString, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(serverlease.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(serverlease.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.MonthlyCost(); ok {
		_spec.SetField(serverlease.FieldMonthlyCost, field.TypeFloat64, value)
		_node.MonthlyCost = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(serverlease.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(serverlease.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := _c.mutation.RenewCycle(); ok {
		_spec.SetField(serverlease.FieldRenewCycle, field.TypeEnum, value)
		_node.RenewCycle = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(serverlease.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ContractNo(); ok {
		_spec.SetField(serverlease.FieldContractNo, field.TypeString, value)
		_node.ContractNo = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(serverlease.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serverlease.TenantTable,
			Columns: []string{serverlease.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serverlease.BillsTable,
			Columns: []string{serverlease.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ServerLeaseCreateBulk is the builder for creating many ServerLease entities in bulk.
type ServerLeaseCreateBulk struct {
	config
	err      error
	builders []*ServerLeaseCreate
}

// Save creates the ServerLease entities in the database.
func (_c *ServerLeaseCreateBulk) Save(ctx context.Context) ([]*ServerLease, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ServerLease, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServerLeaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ServerLeaseCreateBulk) SaveX(ctx context.Context) []*ServerLease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServerLeaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServerLeaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
