// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"starledger/ent/predicate"
	"starledger/ent/tenant"
	"starledger/ent/tenantmodule"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantModuleUpdate is the builder for updating TenantModule entities.
type TenantModuleUpdate struct {
	config
	hooks    []Hook
	mutation *TenantModuleMutation
}

// Where appends a list predicates to the TenantModuleUpdate builder.
func (_u *TenantModuleUpdate) Where(ps ...predicate.TenantModule) *TenantModuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantModuleUpdate) SetUpdatedAt(v time.Time) *TenantModuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantModuleUpdate) SetTenantID(v int) *TenantModuleUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantModuleUpdate) SetNillableTenantID(v *int) *TenantModuleUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetModuleName sets the "module_name" field.
func (_u *TenantModuleUpdate) SetModuleName(v string) *TenantModuleUpdate {
	_u.mutation.SetModuleName(v)
	return _u
}

// SetNillableModuleName sets the "module_name" field if the given value is not nil.
func (_u *TenantModuleUpdate) SetNillableModuleName(v *string) *TenantModuleUpdate {
	if v != nil {
		_u.SetModuleName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TenantModuleUpdate) SetEnabled(v bool) *TenantModuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TenantModuleUpdate) SetNillableEnabled(v *bool) *TenantModuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantModuleUpdate) SetTenant(v *Tenant) *TenantModuleUpdate {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the TenantModuleMutation object of the builder.
func (_u *TenantModuleUpdate) Mutation() *TenantModuleMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantModuleUpdate) ClearTenant() *TenantModuleUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantModuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantModuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantModuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantModuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantModuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantmodule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantModuleUpdate) check() error {
	if v, ok := _u.mutation.ModuleName(); ok {
		if err := tenantmodule.ModuleNameValidator(v); err != nil {
			return &ValidationError{Name: "module_name", err: fmt.Errorf(`ent: validator failed for field "TenantModule.module_name": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantModule.tenant"`)
	}
	return nil
}

func (_u *TenantModuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantmodule.Table, tenantmodule.Columns, sqlgraph.NewFieldSpec(tenantmodule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantmodule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModuleName(); ok {
		_spec.SetField(tenantmodule.FieldModuleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(tenantmodule.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmodule.TenantTable,
			Columns: []string{tenantmodule.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmodule.TenantTable,
			Columns: []string{tenantmodule.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantmodule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantModuleUpdateOne is the builder for updating a single TenantModule entity.
type TenantModuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantModuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantModuleUpdateOne) SetUpdatedAt(v time.Time) *TenantModuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantModuleUpdateOne) SetTenantID(v int) *TenantModuleUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantModuleUpdateOne) SetNillableTenantID(v *int) *TenantModuleUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetModuleName sets the "module_name" field.
func (_u *TenantModuleUpdateOne) SetModuleName(v string) *TenantModuleUpdateOne {
	_u.mutation.SetModuleName(v)
	return _u
}

// SetNillableModuleName sets the "module_name" field if the given value is not nil.
func (_u *TenantModuleUpdateOne) SetNillableModuleName(v *string) *TenantModuleUpdateOne {
	if v != nil {
		_u.SetModuleName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TenantModuleUpdateOne) SetEnabled(v bool) *TenantModuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TenantModuleUpdateOne) SetNillableEnabled(v *bool) *TenantModuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantModuleUpdateOne) SetTenant(v *Tenant) *TenantModuleUpdateOne {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the TenantModuleMutation object of the builder.
func (_u *TenantModuleUpdateOne) Mutation() *TenantModuleMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantModuleUpdateOne) ClearTenant() *TenantModuleUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// Where appends a list predicates to the TenantModuleUpdate builder.
func (_u *TenantModuleUpdateOne) Where(ps ...predicate.TenantModule) *TenantModuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantModuleUpdateOne) Select(field string, fields ...string) *TenantModuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantModule entity.
func (_u *TenantModuleUpdateOne) Save(ctx context.Context) (*TenantModule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantModuleUpdateOne) SaveX(ctx context.Context) *TenantModule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantModuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantModuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantModuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantmodule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantModuleUpdateOne) check() error {
	if v, ok := _u.mutation.ModuleName(); ok {
		if err := tenantmodule.ModuleNameValidator(v); err != nil {
			return &ValidationError{Name: "module_name", err: fmt.Errorf(`ent: validator failed for field "TenantModule.module_name": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantModule.tenant"`)
	}
	return nil
}

func (_u *TenantModuleUpdateOne) sqlSave(ctx context.Context) (_node *TenantModule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantmodule.Table, tenantmodule.Columns, sqlgraph.NewFieldSpec(tenantmodule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantModule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantmodule.FieldID)
		for _, f := range fields {
			if !tenantmodule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantmodule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantmodule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModuleName(); ok {
		_spec.SetField(tenantmodule.FieldModuleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(tenantmodule.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmodule.TenantTable,
			Columns: []string{tenantmodule.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmodule.TenantTable,
			Columns: []string{tenantmodule.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TenantModule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantmodule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
