// Code generated by ent, DO NOT EDIT.

package tenantmodule

import (
	"time"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	Label = "tenant_module"
	FieldID = "id"
	FieldCreatedAt = "created_at"
	FieldUpdatedAt = "updated_at"
	FieldTenantID = "tenant_id"
	FieldModuleName = "module_name"
	FieldEnabled = "enabled"
	EdgeTenant = "tenant"
	Table = "tenant_modules"
	TenantTable = "tenant_modules"
	TenantInverseTable = "tenants"
	TenantColumn = "tenant_id"
)

var Columns = []string{FieldID, FieldCreatedAt, FieldUpdatedAt, FieldTenantID, FieldModuleName, FieldEnabled}

func ValidColumn(column string) bool {
	for i := range Columns { if column == Columns[i] { return true } }
	return false
}

var (
	DefaultCreatedAt func() time.Time
	DefaultUpdatedAt func() time.Time
	UpdateDefaultUpdatedAt func() time.Time
	ModuleNameValidator func(string) error
	DefaultEnabled bool
)

type OrderOption func(*sql.Selector)
func ByID(opts ...sql.OrderTermOption) OrderOption { return sql.OrderByField(FieldID, opts...).ToFunc() }
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption { return sql.OrderByField(FieldCreatedAt, opts...).ToFunc() }
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption { return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc() }
func ByTenantID(opts ...sql.OrderTermOption) OrderOption { return sql.OrderByField(FieldTenantID, opts...).ToFunc() }
func ByModuleName(opts ...sql.OrderTermOption) OrderOption { return sql.OrderByField(FieldModuleName, opts...).ToFunc() }
func ByEnabled(opts ...sql.OrderTermOption) OrderOption { return sql.OrderByField(FieldEnabled, opts...).ToFunc() }
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) { sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...)) }
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(sqlgraph.From(Table, FieldID), sqlgraph.To(TenantInverseTable, FieldID), sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn))
}
