// Code generated by ent, DO NOT EDIT.

package invoice

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the invoice type in the database.
	Label = "invoice"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldBillID holds the string denoting the bill_id field in the database.
	FieldBillID = "bill_id"
	// FieldInvoiceNo holds the string denoting the invoice_no field in the database.
	FieldInvoiceNo = "invoice_no"
	// FieldInvoiceCode holds the string denoting the invoice_code field in the database.
	FieldInvoiceCode = "invoice_code"
	// FieldInvoiceType holds the string denoting the invoice_type field in the database.
	FieldInvoiceType = "invoice_type"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldTaxAmount holds the string denoting the tax_amount field in the database.
	FieldTaxAmount = "tax_amount"
	// FieldTotalAmount holds the string denoting the total_amount field in the database.
	FieldTotalAmount = "total_amount"
	// FieldTaxRate holds the string denoting the tax_rate field in the database.
	FieldTaxRate = "tax_rate"
	// FieldBuyerName holds the string denoting the buyer_name field in the database.
	FieldBuyerName = "buyer_name"
	// FieldBuyerTaxNo holds the string denoting the buyer_tax_no field in the database.
	FieldBuyerTaxNo = "buyer_tax_no"
	// FieldBuyerAddress holds the string denoting the buyer_address field in the database.
	FieldBuyerAddress = "buyer_address"
	// FieldBuyerBank holds the string denoting the buyer_bank field in the database.
	FieldBuyerBank = "buyer_bank"
	// FieldSellerName holds the string denoting the seller_name field in the database.
	FieldSellerName = "seller_name"
	// FieldSellerTaxNo holds the string denoting the seller_tax_no field in the database.
	FieldSellerTaxNo = "seller_tax_no"
	// FieldSellerAddress holds the string denoting the seller_address field in the database.
	FieldSellerAddress = "seller_address"
	// FieldSellerBank holds the string denoting the seller_bank field in the database.
	FieldSellerBank = "seller_bank"
	// FieldInvoiceDate holds the string denoting the invoice_date field in the database.
	FieldInvoiceDate = "invoice_date"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldItemsDetail holds the string denoting the items_detail field in the database.
	FieldItemsDetail = "items_detail"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeBill holds the string denoting the bill edge name in mutations.
	EdgeBill = "bill"
	// Table holds the table name of the invoice in the database.
	Table = "invoices"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "invoices"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// BillTable is the table that holds the bill relation/edge.
	BillTable = "invoices"
	// BillInverseTable is the table name for the Bill entity.
	// It exists in this package in order to avoid circular dependency with the "bill" package.
	BillInverseTable = "bills"
	// BillColumn is the table column denoting the bill relation/edge.
	BillColumn = "bill_id"
)

// Columns holds all SQL columns for invoice fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTenantID,
	FieldBillID,
	FieldInvoiceNo,
	FieldInvoiceCode,
	FieldInvoiceType,
	FieldAmount,
	FieldTaxAmount,
	FieldTotalAmount,
	FieldTaxRate,
	FieldBuyerName,
	FieldBuyerTaxNo,
	FieldBuyerAddress,
	FieldBuyerBank,
	FieldSellerName,
	FieldSellerTaxNo,
	FieldSellerAddress,
	FieldSellerBank,
	FieldInvoiceDate,
	FieldStatus,
	FieldItemsDetail,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// InvoiceNoValidator is a validator for the "invoice_no" field. It is called by the builders before save.
	InvoiceNoValidator func(string) error
	// DefaultInvoiceCode holds the default value on creation for the "invoice_code" field.
	DefaultInvoiceCode string
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultTaxAmount holds the default value on creation for the "tax_amount" field.
	DefaultTaxAmount float64
	// DefaultTotalAmount holds the default value on creation for the "total_amount" field.
	DefaultTotalAmount float64
	// DefaultTaxRate holds the default value on creation for the "tax_rate" field.
	DefaultTaxRate float64
	// DefaultBuyerName holds the default value on creation for the "buyer_name" field.
	DefaultBuyerName string
	// DefaultBuyerTaxNo holds the default value on creation for the "buyer_tax_no" field.
	DefaultBuyerTaxNo string
	// DefaultBuyerAddress holds the default value on creation for the "buyer_address" field.
	DefaultBuyerAddress string
	// DefaultBuyerBank holds the default value on creation for the "buyer_bank" field.
	DefaultBuyerBank string
	// DefaultSellerName holds the default value on creation for the "seller_name" field.
	DefaultSellerName string
	// DefaultSellerTaxNo holds the default value on creation for the "seller_tax_no" field.
	DefaultSellerTaxNo string
	// DefaultSellerAddress holds the default value on creation for the "seller_address" field.
	DefaultSellerAddress string
	// DefaultSellerBank holds the default value on creation for the "seller_bank" field.
	DefaultSellerBank string
	// DefaultItemsDetail holds the default value on creation for the "items_detail" field.
	DefaultItemsDetail string
	// DefaultRemark holds the default value on creation for the "remark" field.
	DefaultRemark string
)

// InvoiceType defines the type for the "invoice_type" enum field.
type InvoiceType string

// InvoiceTypeVatNormal is the default value of the InvoiceType enum.
const DefaultInvoiceType = InvoiceTypeVatNormal

// InvoiceType values.
const (
	InvoiceTypeVatNormal  InvoiceType = "vat_normal"
	InvoiceTypeVatSpecial InvoiceType = "vat_special"
)

func (it InvoiceType) String() string {
	return string(it)
}

// InvoiceTypeValidator is a validator for the "invoice_type" field enum values. It is called by the builders before save.
func InvoiceTypeValidator(it InvoiceType) error {
	switch it {
	case InvoiceTypeVatNormal, InvoiceTypeVatSpecial:
		return nil
	default:
		return fmt.Errorf("invoice: invalid enum value for invoice_type field: %q", it)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusDraft is the default value of the Status enum.
const DefaultStatus = StatusDraft

// Status values.
const (
	StatusDraft     Status = "draft"
	StatusIssued    Status = "issued"
	StatusCancelled Status = "cancelled"
	StatusRed       Status = "red"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDraft, StatusIssued, StatusCancelled, StatusRed:
		return nil
	default:
		return fmt.Errorf("invoice: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Invoice queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByBillID orders the results by the bill_id field.
func ByBillID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillID, opts...).ToFunc()
}

// ByInvoiceNo orders the results by the invoice_no field.
func ByInvoiceNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceNo, opts...).ToFunc()
}

// ByInvoiceCode orders the results by the invoice_code field.
func ByInvoiceCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceCode, opts...).ToFunc()
}

// ByInvoiceType orders the results by the invoice_type field.
func ByInvoiceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceType, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByTaxAmount orders the results by the tax_amount field.
func ByTaxAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxAmount, opts...).ToFunc()
}

// ByTotalAmount orders the results by the total_amount field.
func ByTotalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAmount, opts...).ToFunc()
}

// ByTaxRate orders the results by the tax_rate field.
func ByTaxRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxRate, opts...).ToFunc()
}

// ByBuyerName orders the results by the buyer_name field.
func ByBuyerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerName, opts...).ToFunc()
}

// ByBuyerTaxNo orders the results by the buyer_tax_no field.
func ByBuyerTaxNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerTaxNo, opts...).ToFunc()
}

// ByBuyerAddress orders the results by the buyer_address field.
func ByBuyerAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerAddress, opts...).ToFunc()
}

// ByBuyerBank orders the results by the buyer_bank field.
func ByBuyerBank(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerBank, opts...).ToFunc()
}

// BySellerName orders the results by the seller_name field.
func BySellerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellerName, opts...).ToFunc()
}

// BySellerTaxNo orders the results by the seller_tax_no field.
func BySellerTaxNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellerTaxNo, opts...).ToFunc()
}

// BySellerAddress orders the results by the seller_address field.
func BySellerAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellerAddress, opts...).ToFunc()
}

// BySellerBank orders the results by the seller_bank field.
func BySellerBank(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellerBank, opts...).ToFunc()
}

// ByInvoiceDate orders the results by the invoice_date field.
func ByInvoiceDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceDate, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByItemsDetail orders the results by the items_detail field.
func ByItemsDetail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemsDetail, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByBillField orders the results by bill field.
func ByBillField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBillStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newBillStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BillInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BillTable, BillColumn),
	)
}
