// Code generated by ent, DO NOT EDIT.

package invoice

import (
	"starledger/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTenantID, v))
}

// BillID applies equality check predicate on the "bill_id" field. It's identical to BillIDEQ.
func BillID(v int) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBillID, v))
}

// InvoiceNo applies equality check predicate on the "invoice_no" field. It's identical to InvoiceNoEQ.
func InvoiceNo(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceNo, v))
}

// InvoiceCode applies equality check predicate on the "invoice_code" field. It's identical to InvoiceCodeEQ.
func InvoiceCode(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceCode, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldAmount, v))
}

// TaxAmount applies equality check predicate on the "tax_amount" field. It's identical to TaxAmountEQ.
func TaxAmount(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTaxAmount, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTotalAmount, v))
}

// TaxRate applies equality check predicate on the "tax_rate" field. It's identical to TaxRateEQ.
func TaxRate(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTaxRate, v))
}

// BuyerName applies equality check predicate on the "buyer_name" field. It's identical to BuyerNameEQ.
func BuyerName(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerName, v))
}

// BuyerTaxNo applies equality check predicate on the "buyer_tax_no" field. It's identical to BuyerTaxNoEQ.
func BuyerTaxNo(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerTaxNo, v))
}

// BuyerAddress applies equality check predicate on the "buyer_address" field. It's identical to BuyerAddressEQ.
func BuyerAddress(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerAddress, v))
}

// BuyerBank applies equality check predicate on the "buyer_bank" field. It's identical to BuyerBankEQ.
func BuyerBank(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerBank, v))
}

// SellerName applies equality check predicate on the "seller_name" field. It's identical to SellerNameEQ.
func SellerName(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldSellerName, v))
}

// SellerTaxNo applies equality check predicate on the "seller_tax_no" field. It's identical to SellerTaxNoEQ.
func SellerTaxNo(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldSellerTaxNo, v))
}

// SellerAddress applies equality check predicate on the "seller_address" field. It's identical to SellerAddressEQ.
func SellerAddress(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldSellerAddress, v))
}

// SellerBank applies equality check predicate on the "seller_bank" field. It's identical to SellerBankEQ.
func SellerBank(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldSellerBank, v))
}

// InvoiceDate applies equality check predicate on the "invoice_date" field. It's identical to InvoiceDateEQ.
func InvoiceDate(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceDate, v))
}

// ItemsDetail applies equality check predicate on the "items_detail" field. It's identical to ItemsDetailEQ.
func ItemsDetail(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldItemsDetail, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldTenantID, vs...))
}

// BillIDEQ applies the EQ predicate on the "bill_id" field.
func BillIDEQ(v int) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBillID, v))
}

// BillIDNEQ applies the NEQ predicate on the "bill_id" field.
func BillIDNEQ(v int) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldBillID, v))
}

// BillIDIn applies the In predicate on the "bill_id" field.
func BillIDIn(vs ...int) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldBillID, vs...))
}

// BillIDNotIn applies the NotIn predicate on the "bill_id" field.
func BillIDNotIn(vs ...int) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldBillID, vs...))
}

// BillIDIsNil applies the IsNil predicate on the "bill_id" field.
func BillIDIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldBillID))
}

// BillIDNotNil applies the NotNil predicate on the "bill_id" field.
func BillIDNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldBillID))
}

// InvoiceNoEQ applies the EQ predicate on the "invoice_no" field.
func InvoiceNoEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceNo, v))
}

// InvoiceNoNEQ applies the NEQ predicate on the "invoice_no" field.
func InvoiceNoNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldInvoiceNo, v))
}

// InvoiceNoIn applies the In predicate on the "invoice_no" field.
func InvoiceNoIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldInvoiceNo, vs...))
}

// InvoiceNoNotIn applies the NotIn predicate on the "invoice_no" field.
func InvoiceNoNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldInvoiceNo, vs...))
}

// InvoiceNoGT applies the GT predicate on the "invoice_no" field.
func InvoiceNoGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldInvoiceNo, v))
}

// InvoiceNoGTE applies the GTE predicate on the "invoice_no" field.
func InvoiceNoGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldInvoiceNo, v))
}

// InvoiceNoLT applies the LT predicate on the "invoice_no" field.
func InvoiceNoLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldInvoiceNo, v))
}

// InvoiceNoLTE applies the LTE predicate on the "invoice_no" field.
func InvoiceNoLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldInvoiceNo, v))
}

// InvoiceNoContains applies the Contains predicate on the "invoice_no" field.
func InvoiceNoContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldInvoiceNo, v))
}

// InvoiceNoHasPrefix applies the HasPrefix predicate on the "invoice_no" field.
func InvoiceNoHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldInvoiceNo, v))
}

// InvoiceNoHasSuffix applies the HasSuffix predicate on the "invoice_no" field.
func InvoiceNoHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldInvoiceNo, v))
}

// InvoiceNoEqualFold applies the EqualFold predicate on the "invoice_no" field.
func InvoiceNoEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldInvoiceNo, v))
}

// InvoiceNoContainsFold applies the ContainsFold predicate on the "invoice_no" field.
func InvoiceNoContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldInvoiceNo, v))
}

// InvoiceCodeEQ applies the EQ predicate on the "invoice_code" field.
func InvoiceCodeEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceCode, v))
}

// InvoiceCodeNEQ applies the NEQ predicate on the "invoice_code" field.
func InvoiceCodeNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldInvoiceCode, v))
}

// InvoiceCodeIn applies the In predicate on the "invoice_code" field.
func InvoiceCodeIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldInvoiceCode, vs...))
}

// InvoiceCodeNotIn applies the NotIn predicate on the "invoice_code" field.
func InvoiceCodeNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldInvoiceCode, vs...))
}

// InvoiceCodeGT applies the GT predicate on the "invoice_code" field.
func InvoiceCodeGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldInvoiceCode, v))
}

// InvoiceCodeGTE applies the GTE predicate on the "invoice_code" field.
func InvoiceCodeGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldInvoiceCode, v))
}

// InvoiceCodeLT applies the LT predicate on the "invoice_code" field.
func InvoiceCodeLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldInvoiceCode, v))
}

// InvoiceCodeLTE applies the LTE predicate on the "invoice_code" field.
func InvoiceCodeLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldInvoiceCode, v))
}

// InvoiceCodeContains applies the Contains predicate on the "invoice_code" field.
func InvoiceCodeContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldInvoiceCode, v))
}

// InvoiceCodeHasPrefix applies the HasPrefix predicate on the "invoice_code" field.
func InvoiceCodeHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldInvoiceCode, v))
}

// InvoiceCodeHasSuffix applies the HasSuffix predicate on the "invoice_code" field.
func InvoiceCodeHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldInvoiceCode, v))
}

// InvoiceCodeEqualFold applies the EqualFold predicate on the "invoice_code" field.
func InvoiceCodeEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldInvoiceCode, v))
}

// InvoiceCodeContainsFold applies the ContainsFold predicate on the "invoice_code" field.
func InvoiceCodeContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldInvoiceCode, v))
}

// InvoiceTypeEQ applies the EQ predicate on the "invoice_type" field.
func InvoiceTypeEQ(v InvoiceType) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceType, v))
}

// InvoiceTypeNEQ applies the NEQ predicate on the "invoice_type" field.
func InvoiceTypeNEQ(v InvoiceType) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldInvoiceType, v))
}

// InvoiceTypeIn applies the In predicate on the "invoice_type" field.
func InvoiceTypeIn(vs ...InvoiceType) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldInvoiceType, vs...))
}

// InvoiceTypeNotIn applies the NotIn predicate on the "invoice_type" field.
func InvoiceTypeNotIn(vs ...InvoiceType) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldInvoiceType, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldAmount, v))
}

// TaxAmountEQ applies the EQ predicate on the "tax_amount" field.
func TaxAmountEQ(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTaxAmount, v))
}

// TaxAmountNEQ applies the NEQ predicate on the "tax_amount" field.
func TaxAmountNEQ(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldTaxAmount, v))
}

// TaxAmountIn applies the In predicate on the "tax_amount" field.
func TaxAmountIn(vs ...float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldTaxAmount, vs...))
}

// TaxAmountNotIn applies the NotIn predicate on the "tax_amount" field.
func TaxAmountNotIn(vs ...float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldTaxAmount, vs...))
}

// TaxAmountGT applies the GT predicate on the "tax_amount" field.
func TaxAmountGT(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldTaxAmount, v))
}

// TaxAmountGTE applies the GTE predicate on the "tax_amount" field.
func TaxAmountGTE(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldTaxAmount, v))
}

// TaxAmountLT applies the LT predicate on the "tax_amount" field.
func TaxAmountLT(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldTaxAmount, v))
}

// TaxAmountLTE applies the LTE predicate on the "tax_amount" field.
func TaxAmountLTE(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldTaxAmount, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldTotalAmount, v))
}

// TaxRateEQ applies the EQ predicate on the "tax_rate" field.
func TaxRateEQ(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTaxRate, v))
}

// TaxRateNEQ applies the NEQ predicate on the "tax_rate" field.
func TaxRateNEQ(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldTaxRate, v))
}

// TaxRateIn applies the In predicate on the "tax_rate" field.
func TaxRateIn(vs ...float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldTaxRate, vs...))
}

// TaxRateNotIn applies the NotIn predicate on the "tax_rate" field.
func TaxRateNotIn(vs ...float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldTaxRate, vs...))
}

// TaxRateGT applies the GT predicate on the "tax_rate" field.
func TaxRateGT(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldTaxRate, v))
}

// TaxRateGTE applies the GTE predicate on the "tax_rate" field.
func TaxRateGTE(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldTaxRate, v))
}

// TaxRateLT applies the LT predicate on the "tax_rate" field.
func TaxRateLT(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldTaxRate, v))
}

// TaxRateLTE applies the LTE predicate on the "tax_rate" field.
func TaxRateLTE(v float64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldTaxRate, v))
}

// BuyerNameEQ applies the EQ predicate on the "buyer_name" field.
func BuyerNameEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerName, v))
}

// BuyerNameNEQ applies the NEQ predicate on the "buyer_name" field.
func BuyerNameNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldBuyerName, v))
}

// BuyerNameIn applies the In predicate on the "buyer_name" field.
func BuyerNameIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldBuyerName, vs...))
}

// BuyerNameNotIn applies the NotIn predicate on the "buyer_name" field.
func BuyerNameNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldBuyerName, vs...))
}

// BuyerNameGT applies the GT predicate on the "buyer_name" field.
func BuyerNameGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldBuyerName, v))
}

// BuyerNameGTE applies the GTE predicate on the "buyer_name" field.
func BuyerNameGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldBuyerName, v))
}

// BuyerNameLT applies the LT predicate on the "buyer_name" field.
func BuyerNameLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldBuyerName, v))
}

// BuyerNameLTE applies the LTE predicate on the "buyer_name" field.
func BuyerNameLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldBuyerName, v))
}

// BuyerNameContains applies the Contains predicate on the "buyer_name" field.
func BuyerNameContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldBuyerName, v))
}

// BuyerNameHasPrefix applies the HasPrefix predicate on the "buyer_name" field.
func BuyerNameHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldBuyerName, v))
}

// BuyerNameHasSuffix applies the HasSuffix predicate on the "buyer_name" field.
func BuyerNameHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldBuyerName, v))
}

// BuyerNameEqualFold applies the EqualFold predicate on the "buyer_name" field.
func BuyerNameEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldBuyerName, v))
}

// BuyerNameContainsFold applies the ContainsFold predicate on the "buyer_name" field.
func BuyerNameContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldBuyerName, v))
}

// BuyerTaxNoEQ applies the EQ predicate on the "buyer_tax_no" field.
func BuyerTaxNoEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerTaxNo, v))
}

// BuyerTaxNoNEQ applies the NEQ predicate on the "buyer_tax_no" field.
func BuyerTaxNoNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldBuyerTaxNo, v))
}

// BuyerTaxNoIn applies the In predicate on the "buyer_tax_no" field.
func BuyerTaxNoIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldBuyerTaxNo, vs...))
}

// BuyerTaxNoNotIn applies the NotIn predicate on the "buyer_tax_no" field.
func BuyerTaxNoNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldBuyerTaxNo, vs...))
}

// BuyerTaxNoGT applies the GT predicate on the "buyer_tax_no" field.
func BuyerTaxNoGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldBuyerTaxNo, v))
}

// BuyerTaxNoGTE applies the GTE predicate on the "buyer_tax_no" field.
func BuyerTaxNoGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldBuyerTaxNo, v))
}

// BuyerTaxNoLT applies the LT predicate on the "buyer_tax_no" field.
func BuyerTaxNoLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldBuyerTaxNo, v))
}

// BuyerTaxNoLTE applies the LTE predicate on the "buyer_tax_no" field.
func BuyerTaxNoLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldBuyerTaxNo, v))
}

// BuyerTaxNoContains applies the Contains predicate on the "buyer_tax_no" field.
func BuyerTaxNoContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldBuyerTaxNo, v))
}

// BuyerTaxNoHasPrefix applies the HasPrefix predicate on the "buyer_tax_no" field.
func BuyerTaxNoHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldBuyerTaxNo, v))
}

// BuyerTaxNoHasSuffix applies the HasSuffix predicate on the "buyer_tax_no" field.
func BuyerTaxNoHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldBuyerTaxNo, v))
}

// BuyerTaxNoEqualFold applies the EqualFold predicate on the "buyer_tax_no" field.
func BuyerTaxNoEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldBuyerTaxNo, v))
}

// BuyerTaxNoContainsFold applies the ContainsFold predicate on the "buyer_tax_no" field.
func BuyerTaxNoContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldBuyerTaxNo, v))
}

// BuyerAddressEQ applies the EQ predicate on the "buyer_address" field.
func BuyerAddressEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerAddress, v))
}

// BuyerAddressNEQ applies the NEQ predicate on the "buyer_address" field.
func BuyerAddressNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldBuyerAddress, v))
}

// BuyerAddressIn applies the In predicate on the "buyer_address" field.
func BuyerAddressIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldBuyerAddress, vs...))
}

// BuyerAddressNotIn applies the NotIn predicate on the "buyer_address" field.
func BuyerAddressNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldBuyerAddress, vs...))
}

// BuyerAddressGT applies the GT predicate on the "buyer_address" field.
func BuyerAddressGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldBuyerAddress, v))
}

// BuyerAddressGTE applies the GTE predicate on the "buyer_address" field.
func BuyerAddressGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldBuyerAddress, v))
}

// BuyerAddressLT applies the LT predicate on the "buyer_address" field.
func BuyerAddressLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldBuyerAddress, v))
}

// BuyerAddressLTE applies the LTE predicate on the "buyer_address" field.
func BuyerAddressLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldBuyerAddress, v))
}

// BuyerAddressContains applies the Contains predicate on the "buyer_address" field.
func BuyerAddressContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldBuyerAddress, v))
}

// BuyerAddressHasPrefix applies the HasPrefix predicate on the "buyer_address" field.
func BuyerAddressHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldBuyerAddress, v))
}

// BuyerAddressHasSuffix applies the HasSuffix predicate on the "buyer_address" field.
func BuyerAddressHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldBuyerAddress, v))
}

// BuyerAddressEqualFold applies the EqualFold predicate on the "buyer_address" field.
func BuyerAddressEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldBuyerAddress, v))
}

// BuyerAddressContainsFold applies the ContainsFold predicate on the "buyer_address" field.
func BuyerAddressContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldBuyerAddress, v))
}

// BuyerBankEQ applies the EQ predicate on the "buyer_bank" field.
func BuyerBankEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerBank, v))
}

// BuyerBankNEQ applies the NEQ predicate on the "buyer_bank" field.
func BuyerBankNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldBuyerBank, v))
}

// BuyerBankIn applies the In predicate on the "buyer_bank" field.
func BuyerBankIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldBuyerBank, vs...))
}

// BuyerBankNotIn applies the NotIn predicate on the "buyer_bank" field.
func BuyerBankNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldBuyerBank, vs...))
}

// BuyerBankGT applies the GT predicate on the "buyer_bank" field.
func BuyerBankGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldBuyerBank, v))
}

// BuyerBankGTE applies the GTE predicate on the "buyer_bank" field.
func BuyerBankGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldBuyerBank, v))
}

// BuyerBankLT applies the LT predicate on the "buyer_bank" field.
func BuyerBankLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldBuyerBank, v))
}

// BuyerBankLTE applies the LTE predicate on the "buyer_bank" field.
func BuyerBankLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldBuyerBank, v))
}

// BuyerBankContains applies the Contains predicate on the "buyer_bank" field.
func BuyerBankContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldBuyerBank, v))
}

// BuyerBankHasPrefix applies the HasPrefix predicate on the "buyer_bank" field.
func BuyerBankHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldBuyerBank, v))
}

// BuyerBankHasSuffix applies the HasSuffix predicate on the "buyer_bank" field.
func BuyerBankHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldBuyerBank, v))
}

// BuyerBankEqualFold applies the EqualFold predicate on the "buyer_bank" field.
func BuyerBankEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldBuyerBank, v))
}

// BuyerBankContainsFold applies the ContainsFold predicate on the "buyer_bank" field.
func BuyerBankContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldBuyerBank, v))
}

// SellerNameEQ applies the EQ predicate on the "seller_name" field.
func SellerNameEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldSellerName, v))
}

// SellerNameNEQ applies the NEQ predicate on the "seller_name" field.
func SellerNameNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldSellerName, v))
}

// SellerNameIn applies the In predicate on the "seller_name" field.
func SellerNameIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldSellerName, vs...))
}

// SellerNameNotIn applies the NotIn predicate on the "seller_name" field.
func SellerNameNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldSellerName, vs...))
}

// SellerNameGT applies the GT predicate on the "seller_name" field.
func SellerNameGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldSellerName, v))
}

// SellerNameGTE applies the GTE predicate on the "seller_name" field.
func SellerNameGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldSellerName, v))
}

// SellerNameLT applies the LT predicate on the "seller_name" field.
func SellerNameLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldSellerName, v))
}

// SellerNameLTE applies the LTE predicate on the "seller_name" field.
func SellerNameLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldSellerName, v))
}

// SellerNameContains applies the Contains predicate on the "seller_name" field.
func SellerNameContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldSellerName, v))
}

// SellerNameHasPrefix applies the HasPrefix predicate on the "seller_name" field.
func SellerNameHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldSellerName, v))
}

// SellerNameHasSuffix applies the HasSuffix predicate on the "seller_name" field.
func SellerNameHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldSellerName, v))
}

// SellerNameEqualFold applies the EqualFold predicate on the "seller_name" field.
func SellerNameEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldSellerName, v))
}

// SellerNameContainsFold applies the ContainsFold predicate on the "seller_name" field.
func SellerNameContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldSellerName, v))
}

// SellerTaxNoEQ applies the EQ predicate on the "seller_tax_no" field.
func SellerTaxNoEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldSellerTaxNo, v))
}

// SellerTaxNoNEQ applies the NEQ predicate on the "seller_tax_no" field.
func SellerTaxNoNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldSellerTaxNo, v))
}

// SellerTaxNoIn applies the In predicate on the "seller_tax_no" field.
func SellerTaxNoIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldSellerTaxNo, vs...))
}

// SellerTaxNoNotIn applies the NotIn predicate on the "seller_tax_no" field.
func SellerTaxNoNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldSellerTaxNo, vs...))
}

// SellerTaxNoGT applies the GT predicate on the "seller_tax_no" field.
func SellerTaxNoGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldSellerTaxNo, v))
}

// SellerTaxNoGTE applies the GTE predicate on the "seller_tax_no" field.
func SellerTaxNoGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldSellerTaxNo, v))
}

// SellerTaxNoLT applies the LT predicate on the "seller_tax_no" field.
func SellerTaxNoLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldSellerTaxNo, v))
}

// SellerTaxNoLTE applies the LTE predicate on the "seller_tax_no" field.
func SellerTaxNoLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldSellerTaxNo, v))
}

// SellerTaxNoContains applies the Contains predicate on the "seller_tax_no" field.
func SellerTaxNoContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldSellerTaxNo, v))
}

// SellerTaxNoHasPrefix applies the HasPrefix predicate on the "seller_tax_no" field.
func SellerTaxNoHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldSellerTaxNo, v))
}

// SellerTaxNoHasSuffix applies the HasSuffix predicate on the "seller_tax_no" field.
func SellerTaxNoHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldSellerTaxNo, v))
}

// SellerTaxNoEqualFold applies the EqualFold predicate on the "seller_tax_no" field.
func SellerTaxNoEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldSellerTaxNo, v))
}

// SellerTaxNoContainsFold applies the ContainsFold predicate on the "seller_tax_no" field.
func SellerTaxNoContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldSellerTaxNo, v))
}

// SellerAddressEQ applies the EQ predicate on the "seller_address" field.
func SellerAddressEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldSellerAddress, v))
}

// SellerAddressNEQ applies the NEQ predicate on the "seller_address" field.
func SellerAddressNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldSellerAddress, v))
}

// SellerAddressIn applies the In predicate on the "seller_address" field.
func SellerAddressIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldSellerAddress, vs...))
}

// SellerAddressNotIn applies the NotIn predicate on the "seller_address" field.
func SellerAddressNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldSellerAddress, vs...))
}

// SellerAddressGT applies the GT predicate on the "seller_address" field.
func SellerAddressGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldSellerAddress, v))
}

// SellerAddressGTE applies the GTE predicate on the "seller_address" field.
func SellerAddressGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldSellerAddress, v))
}

// SellerAddressLT applies the LT predicate on the "seller_address" field.
func SellerAddressLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldSellerAddress, v))
}

// SellerAddressLTE applies the LTE predicate on the "seller_address" field.
func SellerAddressLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldSellerAddress, v))
}

// SellerAddressContains applies the Contains predicate on the "seller_address" field.
func SellerAddressContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldSellerAddress, v))
}

// SellerAddressHasPrefix applies the HasPrefix predicate on the "seller_address" field.
func SellerAddressHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldSellerAddress, v))
}

// SellerAddressHasSuffix applies the HasSuffix predicate on the "seller_address" field.
func SellerAddressHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldSellerAddress, v))
}

// SellerAddressEqualFold applies the EqualFold predicate on the "seller_address" field.
func SellerAddressEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldSellerAddress, v))
}

// SellerAddressContainsFold applies the ContainsFold predicate on the "seller_address" field.
func SellerAddressContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldSellerAddress, v))
}

// SellerBankEQ applies the EQ predicate on the "seller_bank" field.
func SellerBankEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldSellerBank, v))
}

// SellerBankNEQ applies the NEQ predicate on the "seller_bank" field.
func SellerBankNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldSellerBank, v))
}

// SellerBankIn applies the In predicate on the "seller_bank" field.
func SellerBankIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldSellerBank, vs...))
}

// SellerBankNotIn applies the NotIn predicate on the "seller_bank" field.
func SellerBankNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldSellerBank, vs...))
}

// SellerBankGT applies the GT predicate on the "seller_bank" field.
func SellerBankGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldSellerBank, v))
}

// SellerBankGTE applies the GTE predicate on the "seller_bank" field.
func SellerBankGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldSellerBank, v))
}

// SellerBankLT applies the LT predicate on the "seller_bank" field.
func SellerBankLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldSellerBank, v))
}

// SellerBankLTE applies the LTE predicate on the "seller_bank" field.
func SellerBankLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldSellerBank, v))
}

// SellerBankContains applies the Contains predicate on the "seller_bank" field.
func SellerBankContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldSellerBank, v))
}

// SellerBankHasPrefix applies the HasPrefix predicate on the "seller_bank" field.
func SellerBankHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldSellerBank, v))
}

// SellerBankHasSuffix applies the HasSuffix predicate on the "seller_bank" field.
func SellerBankHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldSellerBank, v))
}

// SellerBankEqualFold applies the EqualFold predicate on the "seller_bank" field.
func SellerBankEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldSellerBank, v))
}

// SellerBankContainsFold applies the ContainsFold predicate on the "seller_bank" field.
func SellerBankContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldSellerBank, v))
}

// InvoiceDateEQ applies the EQ predicate on the "invoice_date" field.
func InvoiceDateEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceDate, v))
}

// InvoiceDateNEQ applies the NEQ predicate on the "invoice_date" field.
func InvoiceDateNEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldInvoiceDate, v))
}

// InvoiceDateIn applies the In predicate on the "invoice_date" field.
func InvoiceDateIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldInvoiceDate, vs...))
}

// InvoiceDateNotIn applies the NotIn predicate on the "invoice_date" field.
func InvoiceDateNotIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldInvoiceDate, vs...))
}

// InvoiceDateGT applies the GT predicate on the "invoice_date" field.
func InvoiceDateGT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldInvoiceDate, v))
}

// InvoiceDateGTE applies the GTE predicate on the "invoice_date" field.
func InvoiceDateGTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldInvoiceDate, v))
}

// InvoiceDateLT applies the LT predicate on the "invoice_date" field.
func InvoiceDateLT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldInvoiceDate, v))
}

// InvoiceDateLTE applies the LTE predicate on the "invoice_date" field.
func InvoiceDateLTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldInvoiceDate, v))
}

// InvoiceDateIsNil applies the IsNil predicate on the "invoice_date" field.
func InvoiceDateIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldInvoiceDate))
}

// InvoiceDateNotNil applies the NotNil predicate on the "invoice_date" field.
func InvoiceDateNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldInvoiceDate))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldStatus, vs...))
}

// ItemsDetailEQ applies the EQ predicate on the "items_detail" field.
func ItemsDetailEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldItemsDetail, v))
}

// ItemsDetailNEQ applies the NEQ predicate on the "items_detail" field.
func ItemsDetailNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldItemsDetail, v))
}

// ItemsDetailIn applies the In predicate on the "items_detail" field.
func ItemsDetailIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldItemsDetail, vs...))
}

// ItemsDetailNotIn applies the NotIn predicate on the "items_detail" field.
func ItemsDetailNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldItemsDetail, vs...))
}

// ItemsDetailGT applies the GT predicate on the "items_detail" field.
func ItemsDetailGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldItemsDetail, v))
}

// ItemsDetailGTE applies the GTE predicate on the "items_detail" field.
func ItemsDetailGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldItemsDetail, v))
}

// ItemsDetailLT applies the LT predicate on the "items_detail" field.
func ItemsDetailLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldItemsDetail, v))
}

// ItemsDetailLTE applies the LTE predicate on the "items_detail" field.
func ItemsDetailLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldItemsDetail, v))
}

// ItemsDetailContains applies the Contains predicate on the "items_detail" field.
func ItemsDetailContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldItemsDetail, v))
}

// ItemsDetailHasPrefix applies the HasPrefix predicate on the "items_detail" field.
func ItemsDetailHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldItemsDetail, v))
}

// ItemsDetailHasSuffix applies the HasSuffix predicate on the "items_detail" field.
func ItemsDetailHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldItemsDetail, v))
}

// ItemsDetailEqualFold applies the EqualFold predicate on the "items_detail" field.
func ItemsDetailEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldItemsDetail, v))
}

// ItemsDetailContainsFold applies the ContainsFold predicate on the "items_detail" field.
func ItemsDetailContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldItemsDetail, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldRemark, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Invoice {
	return predicate.Invoice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Invoice {
	return predicate.Invoice(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBill applies the HasEdge predicate on the "bill" edge.
func HasBill() predicate.Invoice {
	return predicate.Invoice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BillTable, BillColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBillWith applies the HasEdge predicate on the "bill" edge with a given conditions (other predicates).
func HasBillWith(preds ...predicate.Bill) predicate.Invoice {
	return predicate.Invoice(func(s *sql.Selector) {
		step := newBillStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Invoice) predicate.Invoice {
	return predicate.Invoice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Invoice) predicate.Invoice {
	return predicate.Invoice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Invoice) predicate.Invoice {
	return predicate.Invoice(sql.NotPredicates(p))
}
