// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bill is the predicate function for bill builders.
type Bill func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// ServerLease is the predicate function for serverlease builders.
type ServerLease func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TenantModule is the predicate function for tenantmodule builders.
type TenantModule func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
