// Code generated by ent, DO NOT EDIT.

package bill

import (
	"starledger/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldTenantID, v))
}

// BillNo applies equality check predicate on the "bill_no" field. It's identical to BillNoEQ.
func BillNo(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldBillNo, v))
}

// BillType applies equality check predicate on the "bill_type" field. It's identical to BillTypeEQ.
func BillType(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldBillType, v))
}

// RelatedResourceID applies equality check predicate on the "related_resource_id" field. It's identical to RelatedResourceIDEQ.
func RelatedResourceID(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldRelatedResourceID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldAmount, v))
}

// BillDate applies equality check predicate on the "bill_date" field. It's identical to BillDateEQ.
func BillDate(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldBillDate, v))
}

// DueDate applies equality check predicate on the "due_date" field. It's identical to DueDateEQ.
func DueDate(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldDueDate, v))
}

// PaidDate applies equality check predicate on the "paid_date" field. It's identical to PaidDateEQ.
func PaidDate(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldPaidDate, v))
}

// PaymentMethod applies equality check predicate on the "payment_method" field. It's identical to PaymentMethodEQ.
func PaymentMethod(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldPaymentMethod, v))
}

// InvoiceNo applies equality check predicate on the "invoice_no" field. It's identical to InvoiceNoEQ.
func InvoiceNo(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldInvoiceNo, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldTenantID, vs...))
}

// BillNoEQ applies the EQ predicate on the "bill_no" field.
func BillNoEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldBillNo, v))
}

// BillNoNEQ applies the NEQ predicate on the "bill_no" field.
func BillNoNEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldBillNo, v))
}

// BillNoIn applies the In predicate on the "bill_no" field.
func BillNoIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldBillNo, vs...))
}

// BillNoNotIn applies the NotIn predicate on the "bill_no" field.
func BillNoNotIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldBillNo, vs...))
}

// BillNoGT applies the GT predicate on the "bill_no" field.
func BillNoGT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldBillNo, v))
}

// BillNoGTE applies the GTE predicate on the "bill_no" field.
func BillNoGTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldBillNo, v))
}

// BillNoLT applies the LT predicate on the "bill_no" field.
func BillNoLT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldBillNo, v))
}

// BillNoLTE applies the LTE predicate on the "bill_no" field.
func BillNoLTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldBillNo, v))
}

// BillNoContains applies the Contains predicate on the "bill_no" field.
func BillNoContains(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContains(FieldBillNo, v))
}

// BillNoHasPrefix applies the HasPrefix predicate on the "bill_no" field.
func BillNoHasPrefix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasPrefix(FieldBillNo, v))
}

// BillNoHasSuffix applies the HasSuffix predicate on the "bill_no" field.
func BillNoHasSuffix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasSuffix(FieldBillNo, v))
}

// BillNoEqualFold applies the EqualFold predicate on the "bill_no" field.
func BillNoEqualFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEqualFold(FieldBillNo, v))
}

// BillNoContainsFold applies the ContainsFold predicate on the "bill_no" field.
func BillNoContainsFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContainsFold(FieldBillNo, v))
}

// BillTypeEQ applies the EQ predicate on the "bill_type" field.
func BillTypeEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldBillType, v))
}

// BillTypeNEQ applies the NEQ predicate on the "bill_type" field.
func BillTypeNEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldBillType, v))
}

// BillTypeIn applies the In predicate on the "bill_type" field.
func BillTypeIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldBillType, vs...))
}

// BillTypeNotIn applies the NotIn predicate on the "bill_type" field.
func BillTypeNotIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldBillType, vs...))
}

// BillTypeGT applies the GT predicate on the "bill_type" field.
func BillTypeGT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldBillType, v))
}

// BillTypeGTE applies the GTE predicate on the "bill_type" field.
func BillTypeGTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldBillType, v))
}

// BillTypeLT applies the LT predicate on the "bill_type" field.
func BillTypeLT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldBillType, v))
}

// BillTypeLTE applies the LTE predicate on the "bill_type" field.
func BillTypeLTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldBillType, v))
}

// BillTypeContains applies the Contains predicate on the "bill_type" field.
func BillTypeContains(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContains(FieldBillType, v))
}

// BillTypeHasPrefix applies the HasPrefix predicate on the "bill_type" field.
func BillTypeHasPrefix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasPrefix(FieldBillType, v))
}

// BillTypeHasSuffix applies the HasSuffix predicate on the "bill_type" field.
func BillTypeHasSuffix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasSuffix(FieldBillType, v))
}

// BillTypeEqualFold applies the EqualFold predicate on the "bill_type" field.
func BillTypeEqualFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEqualFold(FieldBillType, v))
}

// BillTypeContainsFold applies the ContainsFold predicate on the "bill_type" field.
func BillTypeContainsFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContainsFold(FieldBillType, v))
}

// RelatedResourceIDEQ applies the EQ predicate on the "related_resource_id" field.
func RelatedResourceIDEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldRelatedResourceID, v))
}

// RelatedResourceIDNEQ applies the NEQ predicate on the "related_resource_id" field.
func RelatedResourceIDNEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldRelatedResourceID, v))
}

// RelatedResourceIDIn applies the In predicate on the "related_resource_id" field.
func RelatedResourceIDIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldRelatedResourceID, vs...))
}

// RelatedResourceIDNotIn applies the NotIn predicate on the "related_resource_id" field.
func RelatedResourceIDNotIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldRelatedResourceID, vs...))
}

// RelatedResourceIDIsNil applies the IsNil predicate on the "related_resource_id" field.
func RelatedResourceIDIsNil() predicate.Bill {
	return predicate.Bill(sql.FieldIsNull(FieldRelatedResourceID))
}

// RelatedResourceIDNotNil applies the NotNil predicate on the "related_resource_id" field.
func RelatedResourceIDNotNil() predicate.Bill {
	return predicate.Bill(sql.FieldNotNull(FieldRelatedResourceID))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldAmount, v))
}

// BillDateEQ applies the EQ predicate on the "bill_date" field.
func BillDateEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldBillDate, v))
}

// BillDateNEQ applies the NEQ predicate on the "bill_date" field.
func BillDateNEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldBillDate, v))
}

// BillDateIn applies the In predicate on the "bill_date" field.
func BillDateIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldBillDate, vs...))
}

// BillDateNotIn applies the NotIn predicate on the "bill_date" field.
func BillDateNotIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldBillDate, vs...))
}

// BillDateGT applies the GT predicate on the "bill_date" field.
func BillDateGT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldBillDate, v))
}

// BillDateGTE applies the GTE predicate on the "bill_date" field.
func BillDateGTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldBillDate, v))
}

// BillDateLT applies the LT predicate on the "bill_date" field.
func BillDateLT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldBillDate, v))
}

// BillDateLTE applies the LTE predicate on the "bill_date" field.
func BillDateLTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldBillDate, v))
}

// DueDateEQ applies the EQ predicate on the "due_date" field.
func DueDateEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldDueDate, v))
}

// DueDateNEQ applies the NEQ predicate on the "due_date" field.
func DueDateNEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldDueDate, v))
}

// DueDateIn applies the In predicate on the "due_date" field.
func DueDateIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldDueDate, vs...))
}

// DueDateNotIn applies the NotIn predicate on the "due_date" field.
func DueDateNotIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldDueDate, vs...))
}

// DueDateGT applies the GT predicate on the "due_date" field.
func DueDateGT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldDueDate, v))
}

// DueDateGTE applies the GTE predicate on the "due_date" field.
func DueDateGTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldDueDate, v))
}

// DueDateLT applies the LT predicate on the "due_date" field.
func DueDateLT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldDueDate, v))
}

// DueDateLTE applies the LTE predicate on the "due_date" field.
func DueDateLTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldDueDate, v))
}

// PaidDateEQ applies the EQ predicate on the "paid_date" field.
func PaidDateEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldPaidDate, v))
}

// PaidDateNEQ applies the NEQ predicate on the "paid_date" field.
func PaidDateNEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldPaidDate, v))
}

// PaidDateIn applies the In predicate on the "paid_date" field.
func PaidDateIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldPaidDate, vs...))
}

// PaidDateNotIn applies the NotIn predicate on the "paid_date" field.
func PaidDateNotIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldPaidDate, vs...))
}

// PaidDateGT applies the GT predicate on the "paid_date" field.
func PaidDateGT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldPaidDate, v))
}

// PaidDateGTE applies the GTE predicate on the "paid_date" field.
func PaidDateGTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldPaidDate, v))
}

// PaidDateLT applies the LT predicate on the "paid_date" field.
func PaidDateLT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldPaidDate, v))
}

// PaidDateLTE applies the LTE predicate on the "paid_date" field.
func PaidDateLTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldPaidDate, v))
}

// PaidDateIsNil applies the IsNil predicate on the "paid_date" field.
func PaidDateIsNil() predicate.Bill {
	return predicate.Bill(sql.FieldIsNull(FieldPaidDate))
}

// PaidDateNotNil applies the NotNil predicate on the "paid_date" field.
func PaidDateNotNil() predicate.Bill {
	return predicate.Bill(sql.FieldNotNull(FieldPaidDate))
}

// PaymentStatusEQ applies the EQ predicate on the "payment_status" field.
func PaymentStatusEQ(v PaymentStatus) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldPaymentStatus, v))
}

// PaymentStatusNEQ applies the NEQ predicate on the "payment_status" field.
func PaymentStatusNEQ(v PaymentStatus) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldPaymentStatus, v))
}

// PaymentStatusIn applies the In predicate on the "payment_status" field.
func PaymentStatusIn(vs ...PaymentStatus) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldPaymentStatus, vs...))
}

// PaymentStatusNotIn applies the NotIn predicate on the "payment_status" field.
func PaymentStatusNotIn(vs ...PaymentStatus) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldPaymentStatus, vs...))
}

// PaymentMethodEQ applies the EQ predicate on the "payment_method" field.
func PaymentMethodEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentMethodNEQ applies the NEQ predicate on the "payment_method" field.
func PaymentMethodNEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldPaymentMethod, v))
}

// PaymentMethodIn applies the In predicate on the "payment_method" field.
func PaymentMethodIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldPaymentMethod, vs...))
}

// PaymentMethodNotIn applies the NotIn predicate on the "payment_method" field.
func PaymentMethodNotIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldPaymentMethod, vs...))
}

// PaymentMethodGT applies the GT predicate on the "payment_method" field.
func PaymentMethodGT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldPaymentMethod, v))
}

// PaymentMethodGTE applies the GTE predicate on the "payment_method" field.
func PaymentMethodGTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldPaymentMethod, v))
}

// PaymentMethodLT applies the LT predicate on the "payment_method" field.
func PaymentMethodLT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldPaymentMethod, v))
}

// PaymentMethodLTE applies the LTE predicate on the "payment_method" field.
func PaymentMethodLTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldPaymentMethod, v))
}

// PaymentMethodContains applies the Contains predicate on the "payment_method" field.
func PaymentMethodContains(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContains(FieldPaymentMethod, v))
}

// PaymentMethodHasPrefix applies the HasPrefix predicate on the "payment_method" field.
func PaymentMethodHasPrefix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasPrefix(FieldPaymentMethod, v))
}

// PaymentMethodHasSuffix applies the HasSuffix predicate on the "payment_method" field.
func PaymentMethodHasSuffix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasSuffix(FieldPaymentMethod, v))
}

// PaymentMethodEqualFold applies the EqualFold predicate on the "payment_method" field.
func PaymentMethodEqualFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEqualFold(FieldPaymentMethod, v))
}

// PaymentMethodContainsFold applies the ContainsFold predicate on the "payment_method" field.
func PaymentMethodContainsFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContainsFold(FieldPaymentMethod, v))
}

// InvoiceNoEQ applies the EQ predicate on the "invoice_no" field.
func InvoiceNoEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldInvoiceNo, v))
}

// InvoiceNoNEQ applies the NEQ predicate on the "invoice_no" field.
func InvoiceNoNEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldInvoiceNo, v))
}

// InvoiceNoIn applies the In predicate on the "invoice_no" field.
func InvoiceNoIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldInvoiceNo, vs...))
}

// InvoiceNoNotIn applies the NotIn predicate on the "invoice_no" field.
func InvoiceNoNotIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldInvoiceNo, vs...))
}

// InvoiceNoGT applies the GT predicate on the "invoice_no" field.
func InvoiceNoGT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldInvoiceNo, v))
}

// InvoiceNoGTE applies the GTE predicate on the "invoice_no" field.
func InvoiceNoGTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldInvoiceNo, v))
}

// InvoiceNoLT applies the LT predicate on the "invoice_no" field.
func InvoiceNoLT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldInvoiceNo, v))
}

// InvoiceNoLTE applies the LTE predicate on the "invoice_no" field.
func InvoiceNoLTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldInvoiceNo, v))
}

// InvoiceNoContains applies the Contains predicate on the "invoice_no" field.
func InvoiceNoContains(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContains(FieldInvoiceNo, v))
}

// InvoiceNoHasPrefix applies the HasPrefix predicate on the "invoice_no" field.
func InvoiceNoHasPrefix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasPrefix(FieldInvoiceNo, v))
}

// InvoiceNoHasSuffix applies the HasSuffix predicate on the "invoice_no" field.
func InvoiceNoHasSuffix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasSuffix(FieldInvoiceNo, v))
}

// InvoiceNoEqualFold applies the EqualFold predicate on the "invoice_no" field.
func InvoiceNoEqualFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEqualFold(FieldInvoiceNo, v))
}

// InvoiceNoContainsFold applies the ContainsFold predicate on the "invoice_no" field.
func InvoiceNoContainsFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContainsFold(FieldInvoiceNo, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContainsFold(FieldRemark, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Bill {
	return predicate.Bill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Bill {
	return predicate.Bill(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasServerLease applies the HasEdge predicate on the "server_lease" edge.
func HasServerLease() predicate.Bill {
	return predicate.Bill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServerLeaseTable, ServerLeaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServerLeaseWith applies the HasEdge predicate on the "server_lease" edge with a given conditions (other predicates).
func HasServerLeaseWith(preds ...predicate.ServerLease) predicate.Bill {
	return predicate.Bill(func(s *sql.Selector) {
		step := newServerLeaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvoices applies the HasEdge predicate on the "invoices" edge.
func HasInvoices() predicate.Bill {
	return predicate.Bill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InvoicesTable, InvoicesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoicesWith applies the HasEdge predicate on the "invoices" edge with a given conditions (other predicates).
func HasInvoicesWith(preds ...predicate.Invoice) predicate.Bill {
	return predicate.Bill(func(s *sql.Selector) {
		step := newInvoicesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bill) predicate.Bill {
	return predicate.Bill(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bill) predicate.Bill {
	return predicate.Bill(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bill) predicate.Bill {
	return predicate.Bill(sql.NotPredicates(p))
}
