// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "username", Type: field.TypeString, Default: ""},
		{Name: "action", Type: field.TypeString},
		{Name: "resource_type", Type: field.TypeString, Default: ""},
		{Name: "resource_id", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "detail", Type: field.TypeString, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Default: ""},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "success"},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audit_logs_tenants_audit_logs",
				Columns:    []*schema.Column{AuditLogsColumns[12]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_tenant_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[12], AuditLogsColumns[1]},
			},
			{
				Name:    "auditlog_tenant_id_action",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[12], AuditLogsColumns[5]},
			},
			{
				Name:    "auditlog_tenant_id_resource_type",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[12], AuditLogsColumns[6]},
			},
			{
				Name:    "auditlog_user_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[3]},
			},
		},
	}
	// BillsColumns holds the columns for the "bills" table.
	BillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "bill_no", Type: field.TypeString, Unique: true},
		{Name: "bill_type", Type: field.TypeString},
		{Name: "amount", Type: field.TypeFloat64, Default: 0},
		{Name: "bill_date", Type: field.TypeTime},
		{Name: "due_date", Type: field.TypeTime},
		{Name: "paid_date", Type: field.TypeTime, Nullable: true},
		{Name: "payment_status", Type: field.TypeEnum, Enums: []string{"pending", "paid", "overdue", "cancelled"}, Default: "pending"},
		{Name: "payment_method", Type: field.TypeString, Default: ""},
		{Name: "invoice_no", Type: field.TypeString, Default: ""},
		{Name: "remark", Type: field.TypeString, Default: ""},
		{Name: "related_resource_id", Type: field.TypeInt, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// BillsTable holds the schema information for the "bills" table.
	BillsTable = &schema.Table{
		Name:       "bills",
		Columns:    BillsColumns,
		PrimaryKey: []*schema.Column{BillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bills_server_leases_bills",
				Columns:    []*schema.Column{BillsColumns[13]},
				RefColumns: []*schema.Column{ServerLeasesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "bills_tenants_bills",
				Columns:    []*schema.Column{BillsColumns[14]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "bill_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{BillsColumns[14]},
			},
			{
				Name:    "bill_bill_no",
				Unique:  false,
				Columns: []*schema.Column{BillsColumns[3]},
			},
			{
				Name:    "bill_bill_type",
				Unique:  false,
				Columns: []*schema.Column{BillsColumns[4]},
			},
			{
				Name:    "bill_payment_status",
				Unique:  false,
				Columns: []*schema.Column{BillsColumns[9]},
			},
			{
				Name:    "bill_due_date",
				Unique:  false,
				Columns: []*schema.Column{BillsColumns[7]},
			},
		},
	}
	// ContractsColumns holds the columns for the "contracts" table.
	ContractsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString},
		{Name: "party_a", Type: field.TypeString, Default: ""},
		{Name: "party_b", Type: field.TypeString, Default: ""},
		{Name: "amount", Type: field.TypeFloat64, Default: 0},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "active", "expired", "terminated"}, Default: "draft"},
		{Name: "file_url", Type: field.TypeString, Default: ""},
		{Name: "remark", Type: field.TypeString, Default: ""},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// ContractsTable holds the schema information for the "contracts" table.
	ContractsTable = &schema.Table{
		Name:       "contracts",
		Columns:    ContractsColumns,
		PrimaryKey: []*schema.Column{ContractsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "contracts_tenants_contracts",
				Columns:    []*schema.Column{ContractsColumns[12]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "contract_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{ContractsColumns[12]},
			},
			{
				Name:    "contract_status",
				Unique:  false,
				Columns: []*schema.Column{ContractsColumns[9]},
			},
			{
				Name:    "contract_end_date",
				Unique:  false,
				Columns: []*schema.Column{ContractsColumns[8]},
			},
		},
	}
	// InvoicesColumns holds the columns for the "invoices" table.
	InvoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "invoice_no", Type: field.TypeString, Unique: true},
		{Name: "invoice_code", Type: field.TypeString, Default: ""},
		{Name: "invoice_type", Type: field.TypeEnum, Enums: []string{"vat_normal", "vat_special"}, Default: "vat_normal"},
		{Name: "amount", Type: field.TypeFloat64, Default: 0},
		{Name: "tax_amount", Type: field.TypeFloat64, Default: 0},
		{Name: "total_amount", Type: field.TypeFloat64, Default: 0},
		{Name: "tax_rate", Type: field.TypeFloat64, Default: 0},
		{Name: "buyer_name", Type: field.TypeString, Default: ""},
		{Name: "buyer_tax_no", Type: field.TypeString, Default: ""},
		{Name: "buyer_address", Type: field.TypeString, Default: ""},
		{Name: "buyer_bank", Type: field.TypeString, Default: ""},
		{Name: "seller_name", Type: field.TypeString, Default: ""},
		{Name: "seller_tax_no", Type: field.TypeString, Default: ""},
		{Name: "seller_address", Type: field.TypeString, Default: ""},
		{Name: "seller_bank", Type: field.TypeString, Default: ""},
		{Name: "invoice_date", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "issued", "cancelled", "red"}, Default: "draft"},
		{Name: "items_detail", Type: field.TypeString, Default: ""},
		{Name: "remark", Type: field.TypeString, Default: ""},
		{Name: "bill_id", Type: field.TypeInt, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// InvoicesTable holds the schema information for the "invoices" table.
	InvoicesTable = &schema.Table{
		Name:       "invoices",
		Columns:    InvoicesColumns,
		PrimaryKey: []*schema.Column{InvoicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invoices_bills_invoices",
				Columns:    []*schema.Column{InvoicesColumns[22]},
				RefColumns: []*schema.Column{BillsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "invoices_tenants_invoices",
				Columns:    []*schema.Column{InvoicesColumns[23]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "invoice_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{InvoicesColumns[23]},
			},
			{
				Name:    "invoice_invoice_no",
				Unique:  false,
				Columns: []*schema.Column{InvoicesColumns[3]},
			},
			{
				Name:    "invoice_status",
				Unique:  false,
				Columns: []*schema.Column{InvoicesColumns[19]},
			},
			{
				Name:    "invoice_bill_id",
				Unique:  false,
				Columns: []*schema.Column{InvoicesColumns[22]},
			},
			{
				Name:    "invoice_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{InvoicesColumns[23], InvoicesColumns[19]},
			},
			{
				Name:    "invoice_tenant_id_invoice_date",
				Unique:  false,
				Columns: []*schema.Column{InvoicesColumns[23], InvoicesColumns[18]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "permissions", Type: field.TypeJSON, Nullable: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "roles_tenants_roles",
				Columns:    []*schema.Column{RolesColumns[6]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "role_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[6]},
			},
		},
	}
	// ServerLeasesColumns holds the columns for the "server_leases" table.
	ServerLeasesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "server_name", Type: field.TypeString},
		{Name: "provider", Type: field.TypeString, Default: ""},
		{Name: "config", Type: field.TypeString, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Default: ""},
		{Name: "location", Type: field.TypeString, Default: ""},
		{Name: "monthly_cost", Type: field.TypeFloat64, Default: 0},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime},
		{Name: "renew_cycle", Type: field.TypeEnum, Enums: []string{"monthly", "quarterly", "yearly"}, Default: "monthly"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "expiring", "expired", "terminated"}, Default: "active"},
		{Name: "contract_no", Type: field.TypeString, Default: ""},
		{Name: "remark", Type: field.TypeString, Default: ""},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// ServerLeasesTable holds the schema information for the "server_leases" table.
	ServerLeasesTable = &schema.Table{
		Name:       "server_leases",
		Columns:    ServerLeasesColumns,
		PrimaryKey: []*schema.Column{ServerLeasesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "server_leases_tenants_server_leases",
				Columns:    []*schema.Column{ServerLeasesColumns[15]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "serverlease_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{ServerLeasesColumns[15]},
			},
			{
				Name:    "serverlease_status",
				Unique:  false,
				Columns: []*schema.Column{ServerLeasesColumns[12]},
			},
			{
				Name:    "serverlease_end_date",
				Unique:  false,
				Columns: []*schema.Column{ServerLeasesColumns[10]},
			},
			{
				Name:    "serverlease_provider",
				Unique:  false,
				Columns: []*schema.Column{ServerLeasesColumns[4]},
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "in_progress", "completed", "cancelled"}, Default: "pending"},
		{Name: "priority", Type: field.TypeEnum, Enums: []string{"low", "medium", "high", "urgent"}, Default: "medium"},
		{Name: "due_date", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "assignee_id", Type: field.TypeInt, Nullable: true},
		{Name: "creator_id", Type: field.TypeInt},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tasks_tenants_tasks",
				Columns:    []*schema.Column{TasksColumns[8]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tasks_users_assigned_tasks",
				Columns:    []*schema.Column{TasksColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "tasks_users_created_tasks",
				Columns:    []*schema.Column{TasksColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "task_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[8]},
			},
			{
				Name:    "task_assignee_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[9]},
			},
			{
				Name:    "task_creator_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[10]},
			},
			{
				Name:    "task_status",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[5]},
			},
			{
				Name:    "task_priority",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[6]},
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"personal", "enterprise", "team"}, Default: "personal"},
		{Name: "contact", Type: field.TypeString, Default: ""},
		{Name: "phone", Type: field.TypeString, Default: ""},
		{Name: "email", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "suspended"}, Default: "active"},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tenant_status",
				Unique:  false,
				Columns: []*schema.Column{TenantsColumns[8]},
			},
		},
	}
	// TenantModulesColumns holds the columns for the "tenant_modules" table.
	TenantModulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "module_name", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// TenantModulesTable holds the schema information for the "tenant_modules" table.
	TenantModulesTable = &schema.Table{
		Name:       "tenant_modules",
		Columns:    TenantModulesColumns,
		PrimaryKey: []*schema.Column{TenantModulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tenant_modules_tenants_modules",
				Columns:    []*schema.Column{TenantModulesColumns[5]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tenantmodule_tenant_id_module_name",
				Unique:  true,
				Columns: []*schema.Column{TenantModulesColumns[5], TenantModulesColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "real_name", Type: field.TypeString, Default: ""},
		{Name: "email", Type: field.TypeString, Default: ""},
		{Name: "phone", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_tenants_users",
				Columns:    []*schema.Column{UsersColumns[9]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[9]},
			},
			{
				Name:    "user_username",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[8]},
			},
		},
	}
	// RoleUsersColumns holds the columns for the "role_users" table.
	RoleUsersColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// RoleUsersTable holds the schema information for the "role_users" table.
	RoleUsersTable = &schema.Table{
		Name:       "role_users",
		Columns:    RoleUsersColumns,
		PrimaryKey: []*schema.Column{RoleUsersColumns[0], RoleUsersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_users_role_id",
				Columns:    []*schema.Column{RoleUsersColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_users_user_id",
				Columns:    []*schema.Column{RoleUsersColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditLogsTable,
		BillsTable,
		ContractsTable,
		InvoicesTable,
		RolesTable,
		ServerLeasesTable,
		TasksTable,
		TenantsTable,
		TenantModulesTable,
		UsersTable,
		RoleUsersTable,
	}
)

func init() {
	AuditLogsTable.ForeignKeys[0].RefTable = TenantsTable
	BillsTable.ForeignKeys[0].RefTable = ServerLeasesTable
	BillsTable.ForeignKeys[1].RefTable = TenantsTable
	ContractsTable.ForeignKeys[0].RefTable = TenantsTable
	InvoicesTable.ForeignKeys[0].RefTable = BillsTable
	InvoicesTable.ForeignKeys[1].RefTable = TenantsTable
	RolesTable.ForeignKeys[0].RefTable = TenantsTable
	ServerLeasesTable.ForeignKeys[0].RefTable = TenantsTable
	TasksTable.ForeignKeys[0].RefTable = TenantsTable
	TasksTable.ForeignKeys[1].RefTable = UsersTable
	TasksTable.ForeignKeys[2].RefTable = UsersTable
	TenantModulesTable.ForeignKeys[0].RefTable = TenantsTable
	UsersTable.ForeignKeys[0].RefTable = TenantsTable
	RoleUsersTable.ForeignKeys[0].RefTable = RolesTable
	RoleUsersTable.ForeignKeys[1].RefTable = UsersTable
}
